/**
 * Diamond ABIs for the worker-side indexer.
 *
 * The two big tuple ABIs (`getOfferDetails` / `getLoanDetails`) used
 * to be hand-typed in this file. That bit us when
 * `LibVaipakam.Offer` gained a `periodicInterestCadence` field and
 * the manual tuple wasn't updated — viem's positional decoder shifted
 * every subsequent field by one slot, producing the OfferBook display
 * bug surfaced in ReleaseNotes-2026-05-05.md.
 *
 * The fix moved those two ABIs to per-facet JSON files generated by
 * `forge inspect <Facet> abi --json` via
 * `contracts/script/exportWatcherAbis.sh`, and re-exported on every
 * deploy via `deploy-chain.sh` / `deploy-mainnet.sh`. The Solidity
 * compiler is now the single source of truth for these tuples — no
 * human-typed positional list to silently drift from the contract
 * struct again.
 *
 * Inline ABIs that survive in this file:
 *   - `ERC721_OWNER_OF_ABI` — single-method, never going to change.
 *   - Event signatures parsed via viem's `parseAbi` in `chainIndexer.ts`
 *     stay inline because event routing uses topic-hash matching, not
 *     positional decode — adding a new field to an event payload
 *     wouldn't silently misalign the way struct returns can.
 */

import OfferCancelFacetAbi from './abis/OfferCancelFacet.json';
import LoanFacetAbi from './abis/LoanFacet.json';

/**
 * Full `OfferCancelFacet` ABI exported from the compiled contract.
 * Hosts `getOfferDetails(uint256) returns (LibVaipakam.Offer)` —
 * the one read this file's tuple-typed export needs to align with.
 * The whole facet ABI is re-exported (not just the one method)
 * because viem's `readContract({ abi, functionName })` accepts any
 * ABI that contains the function; trimming would just be one more
 * thing to forget on a future facet edit.
 */
export const DIAMOND_OFFER_DETAILS_ABI = OfferCancelFacetAbi;

/**
 * Full `LoanFacet` ABI exported from the compiled contract. Hosts
 * `getLoanDetails(uint256) returns (LibVaipakam.Loan)`.
 */
export const DIAMOND_LOAN_DETAILS_ABI = LoanFacetAbi;

/** ERC-721 `ownerOf` — used by the live-ownership multicall in
 *  /loans/by-lender, /loans/by-borrower, /claimables. The Vaipakam
 *  position NFT is a facet on the Diamond, so the diamond address IS
 *  the NFT contract address. Reverts on burned / nonexistent tokens
 *  — caller must catch and treat as "no current holder". */
export const ERC721_OWNER_OF_ABI = [
  {
    type: 'function',
    name: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
] as const;
