import { getAddress, isAddress } from "viem";
import { getDeployment, type Deployment } from "@vaipakam/contracts/deployments";

const env = import.meta.env;

/** Normalises an env-configured address to canonical EIP-55 checksum form.
 *  Ethers v6 throws `bad address checksum` on any mis-cased input, so even a
 *  single wrong letter in `.env.local` bricks every downstream `new Contract(...)`
 *  call. Lowercase-then-`getAddress` round-trips produce the correct form
 *  regardless of how the operator cased the env value, and bad hex still
 *  throws up-front at module load rather than at the first RPC call. */
function normalizeAddress(addr: string | null): string | null {
  if (addr == null) return null;
  const trimmed = addr.trim();
  if (trimmed.length === 0) return null;
  if (!isAddress(trimmed.toLowerCase(), { strict: false })) {
    throw new Error(`Invalid address in env: ${addr}`);
  }
  return getAddress(trimmed.toLowerCase());
}

// #687: nullIfZero (mapped the vpfiBuyPaymentToken address(0) sentinel) was
// removed with the VPFI buy surface.

/**
 * Registry of chains the Vaipakam app is aware of.
 *
 * Phase 1 deploys each Vaipakam Diamond per-chain (no cross-chain protocol
 * state — each network hosts its own independent Diamond instance). Only
 * the VPFI token is cross-chain, via Chainlink CCIP Cross-Chain Token
 * (CCT) pools post-T-068 (2026-05-18): Base hosts the canonical VPFIToken
 * + a CCIP `LockReleaseTokenPool` (lock/release); every other chain
 * hosts a `VPFIMirrorToken` proxy backed by a CCIP `BurnMintTokenPool`.
 * That canonical-vs-mirror split is captured by the `isCanonicalVPFI`
 * flag on each entry.
 *
 * **Source of truth for addresses**: `frontend/src/contracts/deployments.json`,
 * generated by `contracts/script/exportFrontendDeployments.sh` from the
 * canonical per-chain artifacts under `contracts/deployments/<slug>/addresses.json`.
 * After every redeploy, run the export script and the live addresses flow
 * through to the next `vite build`. The static metadata below (chainId,
 * name, blockExplorer, isCanonicalVPFI flag) intentionally stays
 * hand-maintained here — it doesn't change between deploys and is the
 * frontend's authoritative record of what chains the app supports.
 *
 * **What still lives in `.env.local`**: per-chain RPC URLs (the operator's
 * Alchemy/drpc endpoint with API key), WalletConnect project ID, the
 * default chain ID, and a few feature flags. Everything else — Diamond
 * address, vault impl, facet addresses, cross-chain token pool addresses
 * — comes from the consolidated deployments JSON.
 */

// ChainConfig type + the pure compareChainsForDisplay comparator
// were extracted to @vaipakam/contracts in Stage 2c so apps/labs
// (no Vite-bundled runtime registry) can import them without
// pulling this file's import.meta.env-coupled tree. Re-exported
// here so existing callers that import ChainConfig from
// '../contracts/config' (or wagmi-shaped neighbours) keep working.
export type { ChainConfig } from "@vaipakam/contracts/chain-config";
export { compareChainsForDisplay } from "@vaipakam/contracts/chain-config";
import type { ChainConfig } from "@vaipakam/contracts/chain-config";

function str(key: string, fallback: string): string {
  return (env[key] as string | undefined) ?? fallback;
}

/** Static chain metadata — every field that doesn't change between
 *  deploys lives here. The dynamic fields (Diamond address, deploy
 *  block, facet/adapter addresses) are pulled from the deployments
 *  JSON via `buildChainConfig` below. */
interface ChainMeta {
  chainId: number;
  chainIdHex: string;
  name: string;
  shortName: string;
  rpcUrlEnvKey: string;
  rpcUrlDefault: string;
  blockExplorer: string;
  isCanonicalVPFI: boolean;
  testnet: boolean;
  nativeGasSymbol: string;
  nativeGasCoinGeckoSlug: string | null;
  bridgedWethCoinGeckoSlug: string | null;
  /** OfferBook default-pair pre-fills — see ChainConfig docstrings.
   *  Optional on the meta input so chains without sensible defaults
   *  (testnets with deploy-shifting mocks, local Anvil) can omit them
   *  and the {@link buildChainConfig} pass folds null. */
  wrappedNativeAddress?: string | null;
  /** Optional override for the OfferBook default-collateral address
   *  on chains where wrapped-native ≠ bridged-WETH9 (BNB Chain
   *  mainnet, Polygon PoS mainnet). When null/undefined, consumers
   *  fall back to {wrappedNativeAddress} — correct on ETH-native
   *  chains where the two values are identical. Per the 2026-05-14
   *  WETH chain-safety audit + the user-flagged frontend gap. */
  bridgedWethAddress?: string | null;
  predominantStableAddress?: string | null;
}

/** Chains whose Diamond is deployed + present in the shared deployments
 *  bundle for INDEXING, but which are NOT yet user-facing. The indexer reads
 *  the bundle directly (not this frontend registry), so keeping a chain here
 *  lets it be tracked while staying out of the app: `buildChainConfig` folds
 *  `diamondAddress → null` for these, which drops them from `ChainSwitcher`
 *  (filters `diamondAddress !== null`) and flips `isChainSupported` false so
 *  protocol calls are gated off — a user can't select a half-configured chain.
 *
 *  Currently EMPTY — every deployed chain in the bundle is user-facing.
 *
 *  History: BNB testnet (97) sat here from #859 while its cross-chain stack +
 *  diamond were deployed and indexed but its `ConfigureOracle` follow-up hadn't
 *  run (no `wethContract`/ETH feed), so `OracleFacet` fail-closed every asset to
 *  Illiquid. That follow-up landed in #860 (mock-WETH numeraire + real ETH/USD
 *  feed + PancakeSwap-V3 liquidation adapter) and PartialFlows are indexed on 97,
 *  so it graduated to user-facing. (Note: on the testnet the mock WETH is
 *  unpaired, so only the numeraire is deep-liquid — real BNB-testnet assets still
 *  value/route conservatively; an accepted testnet/mirror limitation, not a
 *  reason to hide the chain.) Add a chainId here when a new chain is in the
 *  bundle for indexing but not yet oracle-configured. (#856/#859 Codex.) */
const INDEXER_ONLY_CHAIN_IDS = new Set<number>([]);

/** Folds a `ChainMeta` + the matching deployments-JSON record into a
 *  full `ChainConfig`. RPC URL still comes from the operator's
 *  `.env.local`; everything else flows from the deployments JSON. */
function buildChainConfig(meta: ChainMeta): ChainConfig {
  const dep: Deployment | undefined = getDeployment(meta.chainId);
  const userFacingDiamond = INDEXER_ONLY_CHAIN_IDS.has(meta.chainId)
    ? null
    : (dep?.diamond ?? null);
  return {
    chainId: meta.chainId,
    chainIdHex: meta.chainIdHex,
    name: meta.name,
    shortName: meta.shortName,
    rpcUrl: str(meta.rpcUrlEnvKey, meta.rpcUrlDefault),
    blockExplorer: meta.blockExplorer,
    diamondAddress: userFacingDiamond,
    deployBlock: dep?.deployBlock ?? 0,
    isCanonicalVPFI: meta.isCanonicalVPFI,
    testnet: meta.testnet,
    metricsFacetAddress: dep?.facets?.metricsFacet ?? null,
    vaultImplAddress: dep?.vaultImpl ?? null,
    riskFacetAddress: dep?.facets?.riskFacet ?? null,
    profileFacetAddress: dep?.facets?.profileFacet ?? null,
    nativeGasSymbol: meta.nativeGasSymbol,
    nativeGasCoinGeckoSlug: meta.nativeGasCoinGeckoSlug,
    bridgedWethCoinGeckoSlug: meta.bridgedWethCoinGeckoSlug,
    wrappedNativeAddress: meta.wrappedNativeAddress ?? null,
    bridgedWethAddress: meta.bridgedWethAddress ?? null,
    predominantStableAddress: meta.predominantStableAddress ?? null,
  };
}

// ── Mainnet ──────────────────────────────────────────────────────────────

const ETHEREUM = buildChainConfig({
  chainId: 1,
  chainIdHex: "0x1",
  name: "Ethereum",
  shortName: "eth",
  rpcUrlEnvKey: "VITE_ETHEREUM_RPC_URL",
  rpcUrlDefault: "https://eth.llamarpc.com",
  blockExplorer: "https://etherscan.io",
  isCanonicalVPFI: false,
  testnet: false,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH9
  wrappedNativeAddress: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  // USDC (Circle)
  predominantStableAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
});

const BASE = buildChainConfig({
  chainId: 8453,
  chainIdHex: "0x2105",
  name: "Base",
  shortName: "base",
  rpcUrlEnvKey: "VITE_BASE_RPC_URL",
  rpcUrlDefault: "https://mainnet.base.org",
  blockExplorer: "https://basescan.org",
  isCanonicalVPFI: true,
  testnet: false,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH (Base canonical)
  wrappedNativeAddress: "0x4200000000000000000000000000000000000006",
  // USDC (Circle native)
  predominantStableAddress: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
});

// Polygon PoS was dropped from Phase 1 (weaker multi-sig bridge trust +
// long reorg depth forcing 128+ confirmations). Replaced with Polygon
// zkEVM below, which is a validity-proof rollup on par with Base / Arb /
// Optimism. Re-evaluate PoS for Phase 2 once AggLayer matures.
const POLYGON_ZKEVM = buildChainConfig({
  chainId: 1101,
  chainIdHex: "0x44d",
  name: "Polygon zkEVM",
  shortName: "zkevm",
  rpcUrlEnvKey: "VITE_POLYGON_ZKEVM_RPC_URL",
  rpcUrlDefault: "https://zkevm-rpc.com",
  blockExplorer: "https://zkevm.polygonscan.com",
  isCanonicalVPFI: false,
  // LZ V2 endpoint ID. **Verify against
  // https://docs.layerzero.network/v2/deployments/deployed-contracts**
  // before mainnet deploy — the numeric registry evolves.
  testnet: false,
  // Polygon zkEVM uses ETH for gas (not POL/MATIC) — it's a zk-rollup
  // settling on Ethereum, so native gas mirrors mainnet.
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH (bridged via the LXLY bridge)
  wrappedNativeAddress: "0x4F9A0e7FD2Bf6067db6994CF12E4495Df938E6e9",
  // USDC.e (bridged Circle USDC; native USDC not deployed on zkEVM yet)
  predominantStableAddress: "0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035",
});

const BNB = buildChainConfig({
  chainId: 56,
  chainIdHex: "0x38",
  name: "BNB Chain",
  shortName: "bnb",
  rpcUrlEnvKey: "VITE_BNB_RPC_URL",
  rpcUrlDefault: "https://bsc-dataseed.binance.org",
  blockExplorer: "https://bscscan.com",
  isCanonicalVPFI: false,
  testnet: false,
  // BNB Smart Chain mainnet — native gas is BNB. The BuyVPFIAdapter
  // here MUST be in WETH-pull mode (DeployVPFIBuyAdapter pre-flight
  // enforces this — see T-036), so the BuyVPFI page shows the bridged
  // WETH9 ERC20 (`0x2170Ed0880ac9A755fd29B2688956BD959F933F8` per
  // CLAUDE.md) as the actual asset users pay in. Linking BNB
  // separately for users who land here in native-gas testnet mode.
  nativeGasSymbol: "BNB",
  nativeGasCoinGeckoSlug: "binancecoin",
  bridgedWethCoinGeckoSlug: "weth",
  // WBNB — chain's wrapped-native. Kept for chain-native-asset
  // rendering surfaces; NOT the OfferBook default collateral (see
  // bridgedWethAddress below).
  wrappedNativeAddress: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  // Bridged-WETH9 on BNB — the canonical Ethereum-bridged ETH ERC-20
  // (NOT WBNB). Per the 2026-05-14 WETH chain-safety audit, this is
  // what the OfferBook should default to as the collateral filter so
  // users see bridged-ETH-collateral loans on landing, consistent
  // with every other chain. Verify against the chain's official
  // bridge registry before mainnet (CLAUDE.md tracks the canonical
  // address).
  bridgedWethAddress: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
  // USDT — dominant BNB stablecoin (USDC is also widely used but USDT
  // historically wins volume on BSC).
  predominantStableAddress: "0x55d398326f99059fF775485246999027B3197955",
});

const ARBITRUM = buildChainConfig({
  chainId: 42161,
  chainIdHex: "0xa4b1",
  name: "Arbitrum One",
  shortName: "arb",
  rpcUrlEnvKey: "VITE_ARBITRUM_RPC_URL",
  rpcUrlDefault: "https://arb1.arbitrum.io/rpc",
  blockExplorer: "https://arbiscan.io",
  isCanonicalVPFI: false,
  testnet: false,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH (Arbitrum canonical)
  wrappedNativeAddress: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1",
  // USDC (Circle native, not the legacy USDC.e)
  predominantStableAddress: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
});

const OPTIMISM = buildChainConfig({
  chainId: 10,
  chainIdHex: "0xa",
  name: "Optimism",
  shortName: "op",
  rpcUrlEnvKey: "VITE_OPTIMISM_RPC_URL",
  rpcUrlDefault: "https://mainnet.optimism.io",
  blockExplorer: "https://optimistic.etherscan.io",
  isCanonicalVPFI: false,
  testnet: false,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH (OP Stack canonical pre-deploy)
  wrappedNativeAddress: "0x4200000000000000000000000000000000000006",
  // USDC (Circle native, not the legacy USDC.e)
  predominantStableAddress: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
});

// ── Testnet ──────────────────────────────────────────────────────────────

const SEPOLIA = buildChainConfig({
  chainId: 11155111,
  chainIdHex: "0xaa36a7",
  name: "Sepolia",
  shortName: "sep",
  rpcUrlEnvKey: "VITE_SEPOLIA_RPC_URL",
  rpcUrlDefault: "https://rpc.sepolia.org",
  blockExplorer: "https://sepolia.etherscan.io",
  isCanonicalVPFI: false,
  testnet: true,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH9 — Sepolia canonical published in canonicalAssets.ts.
  wrappedNativeAddress: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
  // USDC (Circle testnet)
  predominantStableAddress: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
});

const BASE_SEPOLIA = buildChainConfig({
  chainId: 84532,
  chainIdHex: "0x14a34",
  name: "Base Sepolia",
  shortName: "base-sep",
  rpcUrlEnvKey: "VITE_BASE_SEPOLIA_RPC_URL",
  rpcUrlDefault: "https://sepolia.base.org",
  blockExplorer: "https://sepolia.basescan.org",
  isCanonicalVPFI: true,
  testnet: true,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
  // WETH (Base Sepolia canonical pre-deploy)
  wrappedNativeAddress: "0x4200000000000000000000000000000000000006",
  // USDC (Circle Base Sepolia testnet)
  predominantStableAddress: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
});

// Cardona is the Polygon zkEVM public testnet. Replaces Polygon Amoy from
// Phase 1 — see the POLYGON_ZKEVM comment above for rationale.
const POLYGON_ZKEVM_CARDONA = buildChainConfig({
  chainId: 2442,
  chainIdHex: "0x98a",
  name: "Polygon zkEVM Cardona",
  shortName: "cardona",
  rpcUrlEnvKey: "VITE_POLYGON_ZKEVM_CARDONA_RPC_URL",
  rpcUrlDefault: "https://rpc.cardona.zkevm-rpc.com",
  blockExplorer: "https://cardona-zkevm.polygonscan.com",
  isCanonicalVPFI: false,
  testnet: true,
  // Polygon zkEVM uses ETH for gas (mirror of mainnet zkEVM).
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
});

const BNB_TESTNET = buildChainConfig({
  chainId: 97,
  chainIdHex: "0x61",
  name: "BNB Testnet",
  shortName: "bnb-test",
  rpcUrlEnvKey: "VITE_BNB_TESTNET_RPC_URL",
  rpcUrlDefault: "https://data-seed-prebsc-1-s1.binance.org:8545",
  blockExplorer: "https://testnet.bscscan.com",
  isCanonicalVPFI: false,
  testnet: true,
  // Testnet currently runs the BuyAdapter in native-gas mode (per
  // BNBTestnetDeploy.md §4 — symbolic rate, dev-loop convenience).
  // Mainnet flips to WETH-pull. We populate both slugs so the
  // BuyVPFI card shows the right asset for whichever mode the
  // adapter actually reports at runtime.
  nativeGasSymbol: "tBNB",
  nativeGasCoinGeckoSlug: "binancecoin",
  bridgedWethCoinGeckoSlug: "weth",
});

const ARBITRUM_SEPOLIA = buildChainConfig({
  chainId: 421614,
  chainIdHex: "0x66eee",
  name: "Arbitrum Sepolia",
  shortName: "arb-sep",
  rpcUrlEnvKey: "VITE_ARBITRUM_SEPOLIA_RPC_URL",
  rpcUrlDefault: "https://sepolia-rollup.arbitrum.io/rpc",
  blockExplorer: "https://sepolia.arbiscan.io",
  isCanonicalVPFI: false,
  testnet: true,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
});

const OPTIMISM_SEPOLIA = buildChainConfig({
  chainId: 11155420,
  chainIdHex: "0xaa37dc",
  name: "Optimism Sepolia",
  shortName: "op-sep",
  rpcUrlEnvKey: "VITE_OPTIMISM_SEPOLIA_RPC_URL",
  rpcUrlDefault: "https://sepolia.optimism.io",
  blockExplorer: "https://sepolia-optimistic.etherscan.io",
  isCanonicalVPFI: false,
  testnet: true,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
});

// Anvil — local foundry node used for end-to-end smoke tests.
// Tagged `testnet: true` so every "this is a testnet" UI gate fires
// the same way it does for Sepolia. Diamond / mocks addresses come
// from the anvil deployments JSON written by the bootstrap script.
const ANVIL = buildChainConfig({
  chainId: 31337,
  chainIdHex: "0x7a69",
  name: "Anvil Local",
  shortName: "anvil",
  rpcUrlEnvKey: "VITE_ANVIL_RPC_URL",
  rpcUrlDefault: "http://localhost:8545",
  blockExplorer: "",
  isCanonicalVPFI: false,
  testnet: true,
  nativeGasSymbol: "ETH",
  nativeGasCoinGeckoSlug: "ethereum",
  bridgedWethCoinGeckoSlug: null,
});

// Normalise every deployments-sourced address to canonical EIP-55
// checksum so a mis-cased entry in the per-chain `addresses.json`
// doesn't propagate to `new Contract(addr, ...)` and blow up with
// "bad address checksum" at first use. Done once at module load,
// before the registry publishes the chain objects.
for (const c of [
  ETHEREUM,
  BASE,
  POLYGON_ZKEVM,
  ARBITRUM,
  OPTIMISM,
  BNB,
  SEPOLIA,
  BASE_SEPOLIA,
  POLYGON_ZKEVM_CARDONA,
  ARBITRUM_SEPOLIA,
  OPTIMISM_SEPOLIA,
  BNB_TESTNET,
  ANVIL,
]) {
  c.diamondAddress = normalizeAddress(c.diamondAddress);
  c.metricsFacetAddress = normalizeAddress(c.metricsFacetAddress);
  c.vaultImplAddress = normalizeAddress(c.vaultImplAddress);
  c.riskFacetAddress = normalizeAddress(c.riskFacetAddress);
  c.profileFacetAddress = normalizeAddress(c.profileFacetAddress);
}

export const CHAIN_REGISTRY: Record<number, ChainConfig> = {
  [ETHEREUM.chainId]: ETHEREUM,
  [BASE.chainId]: BASE,
  [POLYGON_ZKEVM.chainId]: POLYGON_ZKEVM,
  [ARBITRUM.chainId]: ARBITRUM,
  [OPTIMISM.chainId]: OPTIMISM,
  [BNB.chainId]: BNB,
  [SEPOLIA.chainId]: SEPOLIA,
  [BASE_SEPOLIA.chainId]: BASE_SEPOLIA,
  [POLYGON_ZKEVM_CARDONA.chainId]: POLYGON_ZKEVM_CARDONA,
  [ARBITRUM_SEPOLIA.chainId]: ARBITRUM_SEPOLIA,
  [OPTIMISM_SEPOLIA.chainId]: OPTIMISM_SEPOLIA,
  [BNB_TESTNET.chainId]: BNB_TESTNET,
  [ANVIL.chainId]: ANVIL,
};

// ETHEREUM_FAMILY_CHAIN_IDS + compareChainsForDisplay both moved
// to @vaipakam/contracts/chain-config in Stage 2c; the comparator
// is re-exported at the top of this file.

// Explicit operator override. Unset / blank / non-numeric → `NaN`, which
// is never a registry key, so the resolution below falls through to the
// priority order cleanly (no "fake Sepolia default" any more).
const ENV_DEFAULT_CHAIN_ID = (() => {
  const raw = (env.VITE_DEFAULT_CHAIN_ID as string | undefined)?.trim();
  if (!raw) return NaN;
  const n = Number(raw);
  return Number.isFinite(n) ? n : NaN;
})();

/**
 * Read-only fallback chain — used when no wallet is connected, or the
 * wallet is on an unsupported chain.
 *
 * **A deployed mainnet always outranks a deployed testnet.** Resolution
 * order, each step gated on the chain actually having a deployed Diamond:
 *
 *   1. `VITE_DEFAULT_CHAIN_ID` — but honoured *immediately* only if it
 *      points at a deployed **mainnet** chain (operator's explicit pick
 *      among mainnets).
 *   2. First deployed **mainnet** by priority: Ethereum → Base → any
 *      other mainnet (registry order). So once mainnet is live the app
 *      defaults to Ethereum even if `.env.local` still points at a
 *      testnet — a stale env var can't strand the production build on a
 *      testnet after cutover.
 *   3. `VITE_DEFAULT_CHAIN_ID` again — now that no mainnet is live, a
 *      deployed **testnet** env override is honoured (e.g. a build
 *      pinned to a specific testnet rehearsal chain).
 *   4. First deployed **testnet** by priority: Base Sepolia → any other
 *      testnet → Anvil (registry order). Base Sepolia is the Phase-1
 *      canonical testnet for the Stage-3 deploy tree (84532).
 *   5. **Any** chain in the registry with a non-null `diamondAddress` —
 *      fail-soft last resort so a misconfigured rotation never crashes
 *      the page on module load.
 *
 * Type is narrowed: `diamondAddress` is guaranteed non-null so call
 * sites that dereference it don't need a null check.
 */
export type DeployedChain = ChainConfig & { diamondAddress: string };

const isDeployedChain = (c: ChainConfig | undefined): c is DeployedChain =>
  !!c && c.diamondAddress !== null;

/** Deployed chains of the requested tier, in priority order: the named
 *  "heads" first (Ethereum/Base for mainnet; Base Sepolia for testnet),
 *  then everything else of that tier in registry order. */
function deployedChainsByPriority(wantTestnet: boolean): DeployedChain[] {
  const heads: ChainConfig[] = wantTestnet ? [BASE_SEPOLIA] : [ETHEREUM, BASE];
  const headIds = new Set(heads.map((c) => c.chainId));
  const rest = Object.values(CHAIN_REGISTRY).filter(
    (c) => c.testnet === wantTestnet && !headIds.has(c.chainId),
  );
  return [...heads, ...rest].filter(isDeployedChain);
}

export const DEFAULT_CHAIN: DeployedChain = (() => {
  const envChain = CHAIN_REGISTRY[ENV_DEFAULT_CHAIN_ID];

  // 1. explicit env override, if it points at a deployed mainnet.
  if (isDeployedChain(envChain) && !envChain.testnet) return envChain;

  // 2. any deployed mainnet — Ethereum → Base → other mainnets.
  const mainnet = deployedChainsByPriority(false)[0];
  if (mainnet) {
    // Loud nudge if the operator pinned a testnet but mainnet is live —
    // the build is shipping a testnet default into production.
    if (
      isDeployedChain(envChain) &&
      envChain.testnet &&
      typeof console !== "undefined"
    ) {
      console.warn(
        "[DEFAULT_CHAIN] VITE_DEFAULT_CHAIN_ID=" +
          ENV_DEFAULT_CHAIN_ID +
          " is a testnet, but mainnet chain " +
          mainnet.chainId +
          " (" +
          mainnet.name +
          ") is deployed — defaulting to it. Set VITE_DEFAULT_CHAIN_ID " +
          "to a mainnet id (or unset it) to silence this.",
      );
    }
    return mainnet;
  }

  // 3. no mainnet live — honour a deployed testnet env override now.
  if (isDeployedChain(envChain)) return envChain;

  // 4. any deployed testnet — Base Sepolia → other testnets → Anvil.
  const testnet = deployedChainsByPriority(true)[0];
  if (testnet) {
    if (
      !Number.isNaN(ENV_DEFAULT_CHAIN_ID) &&
      typeof console !== "undefined"
    ) {
      console.warn(
        "[DEFAULT_CHAIN] env-chosen chain " +
          ENV_DEFAULT_CHAIN_ID +
          " is not deployed; falling back to " +
          testnet.name +
          " (" +
          testnet.chainId +
          "). Set VITE_DEFAULT_CHAIN_ID at build time to silence this.",
      );
    }
    return testnet;
  }

  // 5. ANY deployed chain — fail-soft last resort. Loud warn: we've
  //    missed the env override AND every mainnet AND every testnet head,
  //    which usually means the deployments JSON shrank or the registry
  //    was rotated. The page boots but treat this as incident-grade.
  for (const c of Object.values(CHAIN_REGISTRY)) {
    if (isDeployedChain(c)) {
      if (typeof console !== "undefined") {
        console.warn(
          "[DEFAULT_CHAIN] no env-chosen, mainnet, or canonical-testnet " +
            "chain has a deployed Diamond; falling through to first " +
            "registry chain with a Diamond — chainId " +
            c.chainId +
            " (" +
            c.name +
            "). Investigate: deployments JSON or CHAIN_REGISTRY rotation likely.",
        );
      }
      return c;
    }
  }
  throw new Error(
    "DEFAULT_CHAIN resolution failed — no chain in CHAIN_REGISTRY has a deployed Diamond",
  );
})();

/**
 * Chain config for the VPFI canonical chain on the current environment
 * (mainnet or testnet). Used by the VPFI panel to show where the canonical
 * adapter lives.
 */
export function getCanonicalVPFIChain(
  preference: "mainnet" | "testnet" = DEFAULT_CHAIN.testnet
    ? "testnet"
    : "mainnet",
): ChainConfig {
  const pool = Object.values(CHAIN_REGISTRY).filter(
    (c) => c.isCanonicalVPFI && c.testnet === (preference === "testnet"),
  );
  return pool[0] ?? BASE_SEPOLIA;
}

/**
 * Back-compat accessor. Prefer `CHAIN_REGISTRY` + `getChainByChainId`.
 */
export const SUPPORTED_CHAINS = {
  ethereum: ETHEREUM,
  base: BASE,
  polygonZkevm: POLYGON_ZKEVM,
  arbitrum: ARBITRUM,
  optimism: OPTIMISM,
  bnb: BNB,
  sepolia: SEPOLIA,
  baseSepolia: BASE_SEPOLIA,
  polygonZkevmCardona: POLYGON_ZKEVM_CARDONA,
  arbitrumSepolia: ARBITRUM_SEPOLIA,
  optimismSepolia: OPTIMISM_SEPOLIA,
  bnbTestnet: BNB_TESTNET,
} as const;

/** Lookup a chain by its numeric chainId. Returns undefined for chains the
 *  app doesn't recognise at all (e.g. Avalanche, Solana — not in scope for
 *  Phase 1). */
export function getChainByChainId(
  chainId: number | null | undefined,
): ChainConfig | undefined {
  if (chainId == null) return undefined;
  return CHAIN_REGISTRY[chainId];
}

/** True iff a live Phase-1 Diamond exists on this chain. Chains registered
 *  but pending deploy (diamondAddress === null) are NOT supported yet —
 *  protocol calls must be gated on this. */
export function isChainSupported(chainId: number | null | undefined): boolean {
  const c = getChainByChainId(chainId);
  return c !== undefined && c.diamondAddress !== null;
}

/** True iff the chain is known to the app (in the registry) even if the
 *  Diamond isn't deployed there yet. Used to distinguish "unsupported chain"
 *  banners from "pending deploy" messaging. */
export function isChainRegistered(chainId: number | null | undefined): boolean {
  return getChainByChainId(chainId) !== undefined;
}
