#!/usr/bin/env tsx
/**
 * Post-build SEO meta injection.
 *
 * Adds three blocks to `dist/index.html`:
 *
 *   - `<link rel="canonical" href="..." />` for the English root.
 *   - `<link rel="alternate" hreflang="X" ...>` siblings pointing at
 *     every supported locale + `x-default` (English).
 *   - `<meta property="og:locale">` plus `og:locale:alternate` entries
 *     so social-card scrapers (Twitter / Discord / Slack) understand
 *     the page is part of a multi-locale set.
 *
 * The HTML body and the lang/title/description stay at their English
 * defaults — the same `dist/index.html` is served for every URL. The
 * React app reads the active URL on hydrate (`LocaleResolver`),
 * switches i18next to the matching locale, applies `dir="rtl"` for
 * Arabic, and re-renders the page with the right copy.
 *
 * Why no per-locale shells anymore
 * --------------------------------
 * Earlier we generated `dist/<locale>/index.html` + `dist/<locale>.html`
 * shells with localised `<html lang>`, `<title>`, and `<meta
 * description>`, plus `_redirects` rewrites pointing at them. That
 * gave crawlers locale-correct meta in the static HTML before JS ran
 * — worth roughly 5–15% organic-traffic uplift on non-English
 * locales — but the rewrite chain interacted badly with Cloudflare
 * Workers Static Assets' default `html_handling: "auto-trailing-
 * slash"`. Each fix uncovered another edge case (loop detector,
 * trailing-slash redirect, .html-vs-directory normalisation
 * conflict) and the deep-link UX kept regressing. We accepted the
 * SEO trade-off and removed the locale shells.
 *
 * What survives:
 *
 *   - Locale-prefixed URLs (`/es/dashboard`, `/ta/help/advanced`)
 *     continue to work — Cloudflare's `not_found_handling:
 *     "single-page-application"` serves `dist/index.html` for any
 *     non-asset request, and React Router routes by URL on the
 *     client.
 *   - hreflang block (this script) tells Google each locale URL is
 *     the canonical version for that language even though the HTML
 *     is shared.
 *   - In-app i18n (10 locales, RTL Arabic, language picker) is
 *     unchanged.
 *   - `sitemap.xml` (separate script) keeps listing all per-locale
 *     URLs.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SUPPORTED_LOCALES } from '../src/i18n/glossary.ts';

const DEFAULT_LOCALE = 'en';
const SITE_URL = (process.env.SITE_URL ?? 'https://vaipakam.com').replace(/\/$/, '');
const DIST_DIR = join(import.meta.dirname ?? new URL('.', import.meta.url).pathname, '..', 'dist');

const OG_LOCALES: Record<string, string> = {
  en: 'en_US',
  es: 'es_ES',
  fr: 'fr_FR',
  de: 'de_DE',
  ja: 'ja_JP',
  zh: 'zh_CN',
  ko: 'ko_KR',
  hi: 'hi_IN',
  ta: 'ta_IN',
  ar: 'ar_AR',
};

function localisedPath(locale: string): string {
  return locale === DEFAULT_LOCALE ? '/' : `/${locale}/`;
}

function metaBlock(): string {
  const lines: string[] = [
    '    <!-- SEO locale alternates (auto-generated by scripts/inject-seo-meta.ts) -->',
    `    <link rel="canonical" href="${SITE_URL}${localisedPath(DEFAULT_LOCALE)}" />`,
  ];
  for (const peer of SUPPORTED_LOCALES) {
    lines.push(
      `    <link rel="alternate" hreflang="${peer}" href="${SITE_URL}${localisedPath(peer)}" />`,
    );
  }
  lines.push(
    `    <link rel="alternate" hreflang="x-default" href="${SITE_URL}${localisedPath(DEFAULT_LOCALE)}" />`,
  );
  const ogLocale = OG_LOCALES[DEFAULT_LOCALE] ?? 'en_US';
  lines.push(`    <meta property="og:locale" content="${ogLocale}" />`);
  for (const peer of SUPPORTED_LOCALES) {
    if (peer === DEFAULT_LOCALE) continue;
    const peerOg = OG_LOCALES[peer];
    if (!peerOg) continue;
    lines.push(`    <meta property="og:locale:alternate" content="${peerOg}" />`);
  }
  return lines.join('\n');
}

function main(): void {
  const indexPath = join(DIST_DIR, 'index.html');
  const html = readFileSync(indexPath, 'utf-8');
  const inject = ['', metaBlock(), ''].join('\n');
  const updated = html.replace(/<\/head>/i, `${inject}  </head>`);
  writeFileSync(indexPath, updated, 'utf-8');
  console.log(`[inject-seo-meta] injected hreflang + OG-locale block into dist/index.html`);
}

main();
