#!/usr/bin/env node
/**
 * Build-time sitemap.xml + robots.txt generator for
 * app.vaipakam.com (same one-script-both-files pattern as
 * apps/www/scripts/generate-sitemap.mjs — robots.txt names the
 * sitemap URL, so generating both in one pass guarantees they agree).
 *
 * Indexing policy (mirrors SeoMeta.tsx — keep the two in sync):
 *   - PUBLIC_ROUTES below are the generic product surfaces — listed
 *     in the sitemap, no robots restrictions.
 *   - Wallet-gated, per-user surfaces (/positions, /claims, /vault,
 *     /activity, /settings, /risk-access, /recover, /faucet) are NOT
 *     Disallowed
 *     here —
 *     deliberately. A robots.txt Disallow prevents crawling but NOT
 *     indexing of the bare URL if it's linked from elsewhere; the
 *     reliable "never index" signal is the noindex the crawler can
 *     only see by fetching the page (SeoMeta's <meta name="robots">
 *     + the X-Robots-Tag rules in public/_headers).
 *
 * No hreflang alternates yet — app's language is a cookie/device
 * preference, not a URL dimension, and TRANSLATED_LOCALES is
 * English-only. When locale URL routing lands (see I18nPlan.md), lift
 * the per-locale <xhtml:link> block from www's generator.
 *
 * Wired to `prebuild` in package.json; output lands in `public/`,
 * which Vite copies verbatim into `dist/`.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readViteEnv } from './viteEnv.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** EMPTY IS UNSET HERE, and `??` does not know that.
 *
 *  `loadEnv` preserves an empty assignment as an empty STRING — which is
 *  the right call in general, since `VAR=` can be a deliberate value.
 *  For an origin it cannot be: an operator who copies `.env.example`
 *  gets `VITE_APP_PUBLIC_ORIGIN=`, the nullish fallback is skipped, and
 *  the prebuild emits `<loc>/analytics</loc>` and `Sitemap: /sitemap.xml`
 *  — relative where the formats require absolute, so the artifacts are
 *  broken for the exact configuration the example documents. Introduced
 *  by making the example assignable in the first place. */
const originFromEnv = (readViteEnv('VITE_APP_PUBLIC_ORIGIN') ?? '').trim();
const ORIGIN = (originFromEnv || 'https://app.vaipakam.com').replace(/\/+$/, '');

/** The protocol console is env-gated: `VITE_ADMIN_DASHBOARD_PUBLIC=false`
 *  (industrial fork, pre-launch deploys) makes the page render only its
 *  hidden-state message. The SEO registry honours the SAME flag with the
 *  SAME default-true semantics, so a restricted deployment never
 *  advertises a surface it withholds — a sitemap entry pointing at a
 *  "visibility is turned off" page is a promise the deployment has
 *  already decided not to keep. Mirrors `apps/www/scripts/seo-routes.mjs`.
 *
 *  Read through `readViteEnv`, not `process.env`: this script would
 *  otherwise default a `.env.production`-hidden console back to public
 *  while the bundle beside it hid the page. */
const PROTOCOL_CONSOLE_PUBLIC =
  (readViteEnv('VITE_ADMIN_DASHBOARD_PUBLIC') ?? '').toLowerCase() !== 'false';

/** Indexable routes — mirrors the `index: true` rows in
 *  src/components/SeoMeta.tsx. Order: likely-importance for a
 *  crawler's first-pass scan. */
const PUBLIC_ROUTES = [
  '/',
  '/borrow',
  '/lend',
  '/rent',
  '/offers',
  '/desk',
  '/vpfi',
  '/nft',
  '/help',
  '/analytics',
  // Conditional, unlike every other entry here — see the flag above.
  ...(PROTOCOL_CONSOLE_PUBLIC ? ['/protocol-console'] : []),
];

function buildSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ];
  for (const route of PUBLIC_ROUTES) {
    lines.push('  <url>');
    lines.push(`    <loc>${ORIGIN}${route === '/' ? '/' : route}</loc>`);
    lines.push(`    <lastmod>${today}</lastmod>`);
    lines.push(`    <priority>${route === '/' ? '1.0' : '0.7'}</priority>`);
    lines.push('  </url>');
  }
  lines.push('</urlset>');
  return lines.join('\n') + '\n';
}

function buildRobots() {
  return [
    '# Vaipakam connected app (app) — public crawl policy.',
    '# Generated by apps/app/scripts/generate-seo.mjs',
    `# at ${new Date().toISOString()}`,
    '#',
    '# Per-user surfaces are excluded from the index via noindex',
    '# (meta tag + X-Robots-Tag in _headers), NOT via Disallow —',
    '# see the generator header for why.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n');
}

const publicDir = resolve(__dirname, '..', 'public');
mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'sitemap.xml'), buildSitemap());
writeFileSync(resolve(publicDir, 'robots.txt'), buildRobots());
console.log(
  `[seo] wrote sitemap.xml (${PUBLIC_ROUTES.length} URLs) + robots.txt → ${publicDir}`,
);
