#!/usr/bin/env node
/**
 * Build-time sitemap.xml + robots.txt generator for
 * app.vaipakam.com (same one-script-both-files pattern as
 * apps/www/scripts/generate-sitemap.mjs — robots.txt names the
 * sitemap URL, so generating both in one pass guarantees they agree).
 *
 * Indexing policy (mirrors SeoMeta.tsx — keep the two in sync):
 *   - PUBLIC_ROUTES below are the generic product surfaces — listed
 *     in the sitemap, no robots restrictions.
 *   - Wallet-gated, per-user surfaces (/positions, /claims, /vault,
 *     /activity, /settings, /risk-access, /recover, /faucet) are NOT
 *     Disallowed
 *     here —
 *     deliberately. A robots.txt Disallow prevents crawling but NOT
 *     indexing of the bare URL if it's linked from elsewhere; the
 *     reliable "never index" signal is the noindex the crawler can
 *     only see by fetching the page (SeoMeta's <meta name="robots">
 *     + the X-Robots-Tag rules in public/_headers).
 *
 * No hreflang alternates yet — app's language is a cookie/device
 * preference, not a URL dimension, and TRANSLATED_LOCALES is
 * English-only. When locale URL routing lands (see I18nPlan.md), lift
 * the per-locale <xhtml:link> block from www's generator.
 *
 * Wired to `prebuild` in package.json; output lands in `public/`,
 * which Vite copies verbatim into `dist/`.
 */

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readViteEnv } from './viteEnv.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** EMPTY IS UNSET HERE, and `??` does not know that.
 *
 *  `loadEnv` preserves an empty assignment as an empty STRING — which is
 *  the right call in general, since `VAR=` can be a deliberate value.
 *  For an origin it cannot be: an operator who copies `.env.example`
 *  gets `VITE_APP_PUBLIC_ORIGIN=`, the nullish fallback is skipped, and
 *  the prebuild emits `<loc>/analytics</loc>` and `Sitemap: /sitemap.xml`
 *  — relative where the formats require absolute, so the artifacts are
 *  broken for the exact configuration the example documents. Introduced
 *  by making the example assignable in the first place. */
const originFromEnv = (readViteEnv('VITE_APP_PUBLIC_ORIGIN') ?? '').trim();
const ORIGIN = (originFromEnv || 'https://app.vaipakam.com').replace(/\/+$/, '');

/** The protocol console is env-gated: `VITE_ADMIN_DASHBOARD_PUBLIC=false`
 *  (industrial fork, pre-launch deploys) makes the page render only its
 *  hidden-state message. The SEO registry honours the SAME flag with the
 *  SAME default-true semantics, so a restricted deployment never
 *  advertises a surface it withholds — a sitemap entry pointing at a
 *  "visibility is turned off" page is a promise the deployment has
 *  already decided not to keep. Mirrors `apps/www/scripts/seo-routes.mjs`.
 *
 *  Read through `readViteEnv`, not `process.env`: this script would
 *  otherwise default a `.env.production`-hidden console back to public
 *  while the bundle beside it hid the page. */
const PROTOCOL_CONSOLE_PUBLIC =
  (readViteEnv('VITE_ADMIN_DASHBOARD_PUBLIC') ?? '').toLowerCase() !== 'false';

/** Indexable routes — mirrors the `index: true` rows in
 *  src/components/SeoMeta.tsx. Order: likely-importance for a
 *  crawler's first-pass scan. */
const PUBLIC_ROUTES = [
  '/',
  '/borrow',
  '/lend',
  '/rent',
  '/offers',
  '/desk',
  '/vpfi',
  '/nft',
  '/help',
  '/analytics',
  // Conditional, unlike every other entry here — see the flag above.
  ...(PROTOCOL_CONSOLE_PUBLIC ? ['/protocol-console'] : []),
];

function buildSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ];
  for (const route of PUBLIC_ROUTES) {
    lines.push('  <url>');
    lines.push(`    <loc>${ORIGIN}${route === '/' ? '/' : route}</loc>`);
    lines.push(`    <lastmod>${today}</lastmod>`);
    lines.push(`    <priority>${route === '/' ? '1.0' : '0.7'}</priority>`);
    lines.push('  </url>');
  }
  lines.push('</urlset>');
  return lines.join('\n') + '\n';
}

function buildRobots() {
  return [
    '# Vaipakam connected app (app) — public crawl policy.',
    '# Generated by apps/app/scripts/generate-seo.mjs',
    `# at ${new Date().toISOString()}`,
    '#',
    '# Per-user surfaces are excluded from the index via noindex',
    '# (meta tag + X-Robots-Tag in _headers), NOT via Disallow —',
    '# see the generator header for why.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n');
}

/**
 * `_headers` = the committed `_headers.base` plus whatever this build's
 * flags require.
 *
 * ONE rule is build-dependent and it cannot live in a static file: with
 * `VITE_ADMIN_DASHBOARD_PUBLIC=false` the console renders only its
 * hidden-state message, but `SeoMeta`'s noindex is a React decision, so
 * a crawler that does not execute JavaScript received an indexable HTTP
 * 200 for the surface the deployment had chosen to withhold. `_headers`
 * covered `/protocol-console/*` — the soft-404 children — and not the
 * exact route, which is the one that actually serves the page.
 *
 * When the console IS public (the default, and the retail deploy) the
 * route must stay indexable, so the rule cannot simply be added to the
 * base file. Composing here follows the pattern `sitemap.xml` and
 * `robots.txt` already use: a committed source, a generated output, and
 * the output gitignored.
 */
/**
 * Every SUPPORTED locale prefix, read from the i18n glossary rather
 * than restated here.
 *
 * Parsed out of the TypeScript source because this is a plain `.mjs`
 * build script with no TS loader — and made LOUD rather than lenient:
 * a parse that finds nothing, or implausibly few entries, throws and
 * fails the build. A silent empty list would emit no locale rules at
 * all while the build still succeeded, which is exactly the shape of
 * failure these rules exist to prevent.
 */
function supportedLocales() {
  const src = readFileSync(
    resolve(__dirname, '..', '..', '..', 'packages', 'i18n', 'src', 'glossary.ts'),
    'utf8',
  );
  const block = /export const SUPPORTED_LOCALES = \[([\s\S]*?)\]/.exec(src);
  if (!block) {
    throw new Error(
      '[seo] could not find SUPPORTED_LOCALES in packages/i18n/src/glossary.ts',
    );
  }
  const locales = [...block[1].matchAll(/'([a-z]{2}(?:-[A-Za-z]+)?)'/g)].map(
    (m) => m[1],
  );
  if (locales.length < 5) {
    throw new Error(
      `[seo] parsed only ${locales.length} locales from glossary.ts — refusing` +
        ' to emit locale header rules from a list that is almost certainly wrong',
    );
  }
  return locales;
}

/**
 * `noindex` for every locale-prefixed URL.
 *
 * The retired deployment mounted every route under `/:locale`, so
 * `/es/positions/7` and `/de/analytics` are real bookmarks this app now
 * answers — with a redirect that strips the prefix. But that redirect
 * is a React route: a crawler that does not execute the SPA receives
 * the generic indexable 200 shell and never runs it, nor `SeoMeta`. The
 * per-user surfaces below are protected by exact-path rules that a
 * locale prefix walks straight past (Codex round 29 P2).
 *
 * Blanket `noindex` on the whole prefix rather than mirroring each
 * destination's rule, because that is the stronger AND simpler
 * statement: a locale-prefixed URL is never canonical in this app. For
 * a per-user route it restores the protection the unprefixed path has;
 * for a public one it prevents a duplicate of a page that already has a
 * canonical address. Nothing is lost either way — the destination is
 * what should be indexed.
 */
function localeHeaderRules() {
  const rules = supportedLocales()
    .flatMap((loc) => [`/${loc}`, `  X-Robots-Tag: noindex`, `/${loc}/*`, `  X-Robots-Tag: noindex`])
    .join('\n');
  return (
    '\n# Generated by scripts/generate-seo.mjs — locale-prefixed aliases\n' +
    '# from the retired deployment. These are compatibility redirects,\n' +
    '# never canonical URLs, and a non-JS crawler never runs the redirect\n' +
    '# that would take it to the real page. See localeHeaderRules().\n' +
    rules +
    '\n'
  );
}

function buildHeaders() {
  const base =
    readFileSync(resolve(__dirname, '..', 'public', '_headers.base'), 'utf8').replace(
      /\n*$/,
      '\n',
    ) + localeHeaderRules();
  if (PROTOCOL_CONSOLE_PUBLIC) return base;
  return (
    base.replace(/\n*$/, '\n') +
    '\n# Generated by scripts/generate-seo.mjs —' +
    ' VITE_ADMIN_DASHBOARD_PUBLIC=false on this build.\n' +
    '# The EXACT route, which `/protocol-console/*` does not cover: the\n' +
    '# page renders only its hidden-state message here, and a crawler\n' +
    '# that does not run JS would otherwise index it from the 200 shell.\n' +
    '/protocol-console\n' +
    '  X-Robots-Tag: noindex\n'
  );
}

const publicDir = resolve(__dirname, '..', 'public');
mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'sitemap.xml'), buildSitemap());
writeFileSync(resolve(publicDir, 'robots.txt'), buildRobots());
writeFileSync(resolve(publicDir, '_headers'), buildHeaders());
console.log(
  `[seo] wrote sitemap.xml (${PUBLIC_ROUTES.length} URLs) + robots.txt` +
    ` + _headers (console ${PROTOCOL_CONSOLE_PUBLIC ? 'public' : 'HIDDEN'}) → ${publicDir}`,
);
