import { getAddress, isAddress } from 'viem';
import { getDeployment, type Deployment } from './deployments';

const env = import.meta.env;

/** Normalises an env-configured address to canonical EIP-55 checksum form.
 *  Ethers v6 throws `bad address checksum` on any mis-cased input, so even a
 *  single wrong letter in `.env.local` bricks every downstream `new Contract(...)`
 *  call. Lowercase-then-`getAddress` round-trips produce the correct form
 *  regardless of how the operator cased the env value, and bad hex still
 *  throws up-front at module load rather than at the first RPC call. */
function normalizeAddress(addr: string | null): string | null {
  if (addr == null) return null;
  const trimmed = addr.trim();
  if (trimmed.length === 0) return null;
  if (!isAddress(trimmed.toLowerCase(), { strict: false })) {
    throw new Error(`Invalid address in env: ${addr}`);
  }
  return getAddress(trimmed.toLowerCase());
}

/** Solidity convention: `address(0)` in the `vpfiBuyPaymentToken` slot
 *  means "pay in native gas (ETH / BNB)". The TS layer prefers `null`
 *  for that case to keep JS-truthiness checks honest, so map at the
 *  deployments-JSON boundary. */
const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000';
function nullIfZero(addr: string | undefined): string | null {
  if (addr == null) return null;
  if (addr.toLowerCase() === ZERO_ADDRESS) return null;
  return addr;
}

/**
 * Registry of chains the Vaipakam app is aware of.
 *
 * Phase 1 deploys each Vaipakam Diamond per-chain (no cross-chain protocol
 * state — each network hosts its own independent Diamond instance). Only
 * the VPFI token is cross-chain, via LayerZero OFT V2: Base hosts the
 * canonical VPFIToken + OFT Adapter (lock/release); every other chain
 * hosts a pure OFT mirror (burn/mint). That split is captured by the
 * `isCanonicalVPFI` flag on each entry.
 *
 * **Source of truth for addresses**: `frontend/src/contracts/deployments.json`,
 * generated by `contracts/script/exportFrontendDeployments.sh` from the
 * canonical per-chain artifacts under `contracts/deployments/<slug>/addresses.json`.
 * After every redeploy, run the export script and the live addresses flow
 * through to the next `vite build`. The static metadata below (chainId,
 * name, blockExplorer, lzEid, isCanonicalVPFI flag) intentionally stays
 * hand-maintained here — it doesn't change between deploys and is the
 * frontend's authoritative record of what chains the app supports.
 *
 * **What still lives in `.env.local`**: per-chain RPC URLs (the operator's
 * Alchemy/drpc endpoint with API key), WalletConnect project ID, the
 * default chain ID, and a few feature flags. Everything else — Diamond
 * address, escrow impl, facet addresses, LZ adapter addresses — comes
 * from the consolidated deployments JSON.
 */

export interface ChainConfig {
  chainId: number;
  chainIdHex: string;
  name: string;
  shortName: string;
  rpcUrl: string;
  blockExplorer: string;
  /** Diamond proxy address on this chain, or null if Phase 1 hasn't deployed
   *  here yet. Callers must gate protocol calls on non-null. */
  diamondAddress: string | null;
  /** Block containing the Diamond creation tx. 0 when diamondAddress is null. */
  deployBlock: number;
  /** True on the chain that hosts the canonical VPFIToken + OFT Adapter
   *  (lock/release). False on mirror chains (burn/mint). Exactly one
   *  mainnet entry and one testnet entry should be true. */
  isCanonicalVPFI: boolean;
  /** LayerZero V2 endpoint id, or null when no OFT endpoint is wired here. */
  lzEid: number | null;
  /** Testnet vs mainnet — used only for UI grouping. */
  testnet: boolean;
  /** VPFIBuyAdapter address on this chain, or null when buys here route
   *  directly through the Diamond (canonical) or the adapter hasn't been
   *  deployed yet. Mirror chains with a null adapter cannot originate
   *  cross-chain buys. */
  vpfiBuyAdapter: string | null;
  /** When set, the adapter pulls this ERC20 for `amountIn` (WETH mode) so
   *  the user only has to send the LayerZero native fee as `msg.value`.
   *  Null = native ETH mode (default). Ignored when `vpfiBuyAdapter` is null. */
  vpfiBuyPaymentToken: string | null;
  /** Standalone MetricsFacet implementation address (not the Diamond) on
   *  this chain. Surfaces on the Analytics page's Transparency & Source
   *  card so users can land directly on the facet's `#readContract` tab
   *  on the block explorer. Null falls back to the Diamond proxy. */
  metricsFacetAddress: string | null;
  /** UUPS escrow implementation deployed by `EscrowFactoryFacet`. Null
   *  falls back to the Diamond proxy in the Security card. */
  escrowImplAddress: string | null;
  /** Standalone RiskFacet implementation address. Null falls back to
   *  the Diamond proxy. */
  riskFacetAddress: string | null;
  /** Standalone ProfileFacet implementation address. Null falls back
   *  to the Diamond proxy. */
  profileFacetAddress: string | null;
  /** Symbol of this chain's native gas token — used in the BuyVPFI
   *  card and balance displays so the UI says "ETH" / "BNB" / "POL"
   *  appropriately rather than always "ETH". On native-gas-mode buy
   *  adapter chains this is also what the user actually pays in. */
  nativeGasSymbol: string;
  /** CoinGecko coin slug for this chain's native gas token. Used to
   *  render a deep-link from the BuyVPFI asset symbol so users can
   *  cross-reference exactly which asset they need to acquire (and
   *  on which chain, since WETH on BNB ≠ WETH on Polygon — different
   *  bridged contracts even though both use the symbol "WETH").
   *  Null when no canonical CoinGecko page exists. */
  nativeGasCoinGeckoSlug: string | null;
  /** CoinGecko slug for the chain's canonical bridged WETH9 ERC20.
   *  Only meaningful when the BuyAdapter is in WETH-pull mode
   *  (`vpfiBuyPaymentToken != null`); the BuyVPFI card uses this
   *  to link the "WETH" label to the right CoinGecko page for the
   *  chain's specific bridged variant. Null on chains where the
   *  adapter is in native-gas mode (no WETH user-facing) or where
   *  no canonical CoinGecko page tracks the bridged WETH. */
  bridgedWethCoinGeckoSlug: string | null;
}

function str(key: string, fallback: string): string {
  return (env[key] as string | undefined) ?? fallback;
}

/** Static chain metadata — every field that doesn't change between
 *  deploys lives here. The dynamic fields (Diamond address, deploy
 *  block, facet/adapter addresses) are pulled from the deployments
 *  JSON via `buildChainConfig` below. */
interface ChainMeta {
  chainId: number;
  chainIdHex: string;
  name: string;
  shortName: string;
  rpcUrlEnvKey: string;
  rpcUrlDefault: string;
  blockExplorer: string;
  isCanonicalVPFI: boolean;
  lzEid: number | null;
  testnet: boolean;
  nativeGasSymbol: string;
  nativeGasCoinGeckoSlug: string | null;
  bridgedWethCoinGeckoSlug: string | null;
}

/** Folds a `ChainMeta` + the matching deployments-JSON record into a
 *  full `ChainConfig`. RPC URL still comes from the operator's
 *  `.env.local`; everything else flows from the deployments JSON. */
function buildChainConfig(meta: ChainMeta): ChainConfig {
  const dep: Deployment | undefined = getDeployment(meta.chainId);
  return {
    chainId: meta.chainId,
    chainIdHex: meta.chainIdHex,
    name: meta.name,
    shortName: meta.shortName,
    rpcUrl: str(meta.rpcUrlEnvKey, meta.rpcUrlDefault),
    blockExplorer: meta.blockExplorer,
    diamondAddress: dep?.diamond ?? null,
    deployBlock: dep?.deployBlock ?? 0,
    isCanonicalVPFI: meta.isCanonicalVPFI,
    lzEid: meta.lzEid,
    testnet: meta.testnet,
    vpfiBuyAdapter: dep?.vpfiBuyAdapter ?? null,
    vpfiBuyPaymentToken: nullIfZero(dep?.vpfiBuyPaymentToken),
    metricsFacetAddress: dep?.facets?.metricsFacet ?? null,
    escrowImplAddress: dep?.escrowImpl ?? null,
    riskFacetAddress: dep?.facets?.riskFacet ?? null,
    profileFacetAddress: dep?.facets?.profileFacet ?? null,
    nativeGasSymbol: meta.nativeGasSymbol,
    nativeGasCoinGeckoSlug: meta.nativeGasCoinGeckoSlug,
    bridgedWethCoinGeckoSlug: meta.bridgedWethCoinGeckoSlug,
  };
}

// ── Mainnet ──────────────────────────────────────────────────────────────

const ETHEREUM = buildChainConfig({
  chainId: 1,
  chainIdHex: '0x1',
  name: 'Ethereum',
  shortName: 'eth',
  rpcUrlEnvKey: 'VITE_ETHEREUM_RPC_URL',
  rpcUrlDefault: 'https://eth.llamarpc.com',
  blockExplorer: 'https://etherscan.io',
  isCanonicalVPFI: false,
  lzEid: 30101,
  testnet: false,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const BASE = buildChainConfig({
  chainId: 8453,
  chainIdHex: '0x2105',
  name: 'Base',
  shortName: 'base',
  rpcUrlEnvKey: 'VITE_BASE_RPC_URL',
  rpcUrlDefault: 'https://mainnet.base.org',
  blockExplorer: 'https://basescan.org',
  isCanonicalVPFI: true,
  lzEid: 30184,
  testnet: false,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

// Polygon PoS was dropped from Phase 1 (weaker multi-sig bridge trust +
// long reorg depth forcing 128+ confirmations). Replaced with Polygon
// zkEVM below, which is a validity-proof rollup on par with Base / Arb /
// Optimism. Re-evaluate PoS for Phase 2 once AggLayer matures.
const POLYGON_ZKEVM = buildChainConfig({
  chainId: 1101,
  chainIdHex: '0x44d',
  name: 'Polygon zkEVM',
  shortName: 'zkevm',
  rpcUrlEnvKey: 'VITE_POLYGON_ZKEVM_RPC_URL',
  rpcUrlDefault: 'https://zkevm-rpc.com',
  blockExplorer: 'https://zkevm.polygonscan.com',
  isCanonicalVPFI: false,
  // LZ V2 endpoint ID. **Verify against
  // https://docs.layerzero.network/v2/deployments/deployed-contracts**
  // before mainnet deploy — the numeric registry evolves.
  lzEid: 30267,
  testnet: false,
  // Polygon zkEVM uses ETH for gas (not POL/MATIC) — it's a zk-rollup
  // settling on Ethereum, so native gas mirrors mainnet.
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const BNB = buildChainConfig({
  chainId: 56,
  chainIdHex: '0x38',
  name: 'BNB Chain',
  shortName: 'bnb',
  rpcUrlEnvKey: 'VITE_BNB_RPC_URL',
  rpcUrlDefault: 'https://bsc-dataseed.binance.org',
  blockExplorer: 'https://bscscan.com',
  isCanonicalVPFI: false,
  lzEid: 30102,
  testnet: false,
  // BNB Smart Chain mainnet — native gas is BNB. The BuyVPFIAdapter
  // here MUST be in WETH-pull mode (DeployVPFIBuyAdapter pre-flight
  // enforces this — see T-036), so the BuyVPFI page shows the bridged
  // WETH9 ERC20 (`0x2170Ed0880ac9A755fd29B2688956BD959F933F8` per
  // CLAUDE.md) as the actual asset users pay in. Linking BNB
  // separately for users who land here in native-gas testnet mode.
  nativeGasSymbol: 'BNB',
  nativeGasCoinGeckoSlug: 'binancecoin',
  bridgedWethCoinGeckoSlug: 'weth',
});

const ARBITRUM = buildChainConfig({
  chainId: 42161,
  chainIdHex: '0xa4b1',
  name: 'Arbitrum One',
  shortName: 'arb',
  rpcUrlEnvKey: 'VITE_ARBITRUM_RPC_URL',
  rpcUrlDefault: 'https://arb1.arbitrum.io/rpc',
  blockExplorer: 'https://arbiscan.io',
  isCanonicalVPFI: false,
  lzEid: 30110,
  testnet: false,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const OPTIMISM = buildChainConfig({
  chainId: 10,
  chainIdHex: '0xa',
  name: 'Optimism',
  shortName: 'op',
  rpcUrlEnvKey: 'VITE_OPTIMISM_RPC_URL',
  rpcUrlDefault: 'https://mainnet.optimism.io',
  blockExplorer: 'https://optimistic.etherscan.io',
  isCanonicalVPFI: false,
  lzEid: 30111,
  testnet: false,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

// ── Testnet ──────────────────────────────────────────────────────────────

const SEPOLIA = buildChainConfig({
  chainId: 11155111,
  chainIdHex: '0xaa36a7',
  name: 'Sepolia',
  shortName: 'sep',
  rpcUrlEnvKey: 'VITE_SEPOLIA_RPC_URL',
  rpcUrlDefault: 'https://rpc.sepolia.org',
  blockExplorer: 'https://sepolia.etherscan.io',
  isCanonicalVPFI: false,
  lzEid: 40161,
  testnet: true,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const BASE_SEPOLIA = buildChainConfig({
  chainId: 84532,
  chainIdHex: '0x14a34',
  name: 'Base Sepolia',
  shortName: 'base-sep',
  rpcUrlEnvKey: 'VITE_BASE_SEPOLIA_RPC_URL',
  rpcUrlDefault: 'https://sepolia.base.org',
  blockExplorer: 'https://sepolia.basescan.org',
  isCanonicalVPFI: true,
  lzEid: 40245,
  testnet: true,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

// Cardona is the Polygon zkEVM public testnet. Replaces Polygon Amoy from
// Phase 1 — see the POLYGON_ZKEVM comment above for rationale.
const POLYGON_ZKEVM_CARDONA = buildChainConfig({
  chainId: 2442,
  chainIdHex: '0x98a',
  name: 'Polygon zkEVM Cardona',
  shortName: 'cardona',
  rpcUrlEnvKey: 'VITE_POLYGON_ZKEVM_CARDONA_RPC_URL',
  rpcUrlDefault: 'https://rpc.cardona.zkevm-rpc.com',
  blockExplorer: 'https://cardona-zkevm.polygonscan.com',
  isCanonicalVPFI: false,
  lzEid: 40271,
  testnet: true,
  // Polygon zkEVM uses ETH for gas (mirror of mainnet zkEVM).
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const BNB_TESTNET = buildChainConfig({
  chainId: 97,
  chainIdHex: '0x61',
  name: 'BNB Testnet',
  shortName: 'bnb-test',
  rpcUrlEnvKey: 'VITE_BNB_TESTNET_RPC_URL',
  rpcUrlDefault: 'https://data-seed-prebsc-1-s1.binance.org:8545',
  blockExplorer: 'https://testnet.bscscan.com',
  isCanonicalVPFI: false,
  lzEid: 40102,
  testnet: true,
  // Testnet currently runs the BuyAdapter in native-gas mode (per
  // BNBTestnetDeploy.md §4 — symbolic rate, dev-loop convenience).
  // Mainnet flips to WETH-pull. We populate both slugs so the
  // BuyVPFI card shows the right asset for whichever mode the
  // adapter actually reports at runtime.
  nativeGasSymbol: 'tBNB',
  nativeGasCoinGeckoSlug: 'binancecoin',
  bridgedWethCoinGeckoSlug: 'weth',
});

const ARBITRUM_SEPOLIA = buildChainConfig({
  chainId: 421614,
  chainIdHex: '0x66eee',
  name: 'Arbitrum Sepolia',
  shortName: 'arb-sep',
  rpcUrlEnvKey: 'VITE_ARBITRUM_SEPOLIA_RPC_URL',
  rpcUrlDefault: 'https://sepolia-rollup.arbitrum.io/rpc',
  blockExplorer: 'https://sepolia.arbiscan.io',
  isCanonicalVPFI: false,
  lzEid: 40231,
  testnet: true,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

const OPTIMISM_SEPOLIA = buildChainConfig({
  chainId: 11155420,
  chainIdHex: '0xaa37dc',
  name: 'Optimism Sepolia',
  shortName: 'op-sep',
  rpcUrlEnvKey: 'VITE_OPTIMISM_SEPOLIA_RPC_URL',
  rpcUrlDefault: 'https://sepolia.optimism.io',
  blockExplorer: 'https://sepolia-optimistic.etherscan.io',
  isCanonicalVPFI: false,
  lzEid: 40232,
  testnet: true,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

// Anvil — local foundry node used for end-to-end smoke tests.
// Tagged `testnet: true` so every "this is a testnet" UI gate fires
// the same way it does for Sepolia. Diamond / mocks addresses come
// from the anvil deployments JSON written by the bootstrap script.
const ANVIL = buildChainConfig({
  chainId: 31337,
  chainIdHex: '0x7a69',
  name: 'Anvil Local',
  shortName: 'anvil',
  rpcUrlEnvKey: 'VITE_ANVIL_RPC_URL',
  rpcUrlDefault: 'http://localhost:8545',
  blockExplorer: '',
  isCanonicalVPFI: false,
  lzEid: 31337,
  testnet: true,
  nativeGasSymbol: 'ETH',
  nativeGasCoinGeckoSlug: 'ethereum',
  bridgedWethCoinGeckoSlug: null,
});

// Normalise every deployments-sourced address to canonical EIP-55
// checksum so a mis-cased entry in the per-chain `addresses.json`
// doesn't propagate to `new Contract(addr, ...)` and blow up with
// "bad address checksum" at first use. Done once at module load,
// before the registry publishes the chain objects.
for (const c of [
  ETHEREUM,
  BASE,
  POLYGON_ZKEVM,
  ARBITRUM,
  OPTIMISM,
  BNB,
  SEPOLIA,
  BASE_SEPOLIA,
  POLYGON_ZKEVM_CARDONA,
  ARBITRUM_SEPOLIA,
  OPTIMISM_SEPOLIA,
  BNB_TESTNET,
  ANVIL,
]) {
  c.diamondAddress = normalizeAddress(c.diamondAddress);
  c.vpfiBuyAdapter = normalizeAddress(c.vpfiBuyAdapter);
  c.vpfiBuyPaymentToken = normalizeAddress(c.vpfiBuyPaymentToken);
  c.metricsFacetAddress = normalizeAddress(c.metricsFacetAddress);
  c.escrowImplAddress = normalizeAddress(c.escrowImplAddress);
  c.riskFacetAddress = normalizeAddress(c.riskFacetAddress);
  c.profileFacetAddress = normalizeAddress(c.profileFacetAddress);
}

export const CHAIN_REGISTRY: Record<number, ChainConfig> = {
  [ETHEREUM.chainId]: ETHEREUM,
  [BASE.chainId]: BASE,
  [POLYGON_ZKEVM.chainId]: POLYGON_ZKEVM,
  [ARBITRUM.chainId]: ARBITRUM,
  [OPTIMISM.chainId]: OPTIMISM,
  [BNB.chainId]: BNB,
  [SEPOLIA.chainId]: SEPOLIA,
  [BASE_SEPOLIA.chainId]: BASE_SEPOLIA,
  [POLYGON_ZKEVM_CARDONA.chainId]: POLYGON_ZKEVM_CARDONA,
  [ARBITRUM_SEPOLIA.chainId]: ARBITRUM_SEPOLIA,
  [OPTIMISM_SEPOLIA.chainId]: OPTIMISM_SEPOLIA,
  [BNB_TESTNET.chainId]: BNB_TESTNET,
  [ANVIL.chainId]: ANVIL,
};

// Ethereum family (L1 + its canonical testnet) — pinned to the top of every
// chain list so "Ethereum" always reads first. Add new L1/testnet pairs here
// if future chainIds deserve the same placement.
const ETHEREUM_FAMILY_CHAIN_IDS: ReadonlySet<number> = new Set([
  ETHEREUM.chainId, // 1
  SEPOLIA.chainId, // 11155111
]);

/**
 * Canonical display order for any list of ChainConfig:
 *   1. Mainnets before testnets.
 *   2. Within each tier, Ethereum family (mainnet + Sepolia) pinned first.
 *   3. Rest alphabetical by display name.
 *
 * Import and use this wherever chains are surfaced to the user — selectors,
 * badges, analytics tables — so the ordering stays consistent across every
 * surface and the user always sees Ethereum at the top of its tier.
 */
export function compareChainsForDisplay(
  a: ChainConfig,
  b: ChainConfig,
): number {
  const tierDiff = Number(a.testnet) - Number(b.testnet);
  if (tierDiff !== 0) return tierDiff;
  const aEth = ETHEREUM_FAMILY_CHAIN_IDS.has(a.chainId);
  const bEth = ETHEREUM_FAMILY_CHAIN_IDS.has(b.chainId);
  if (aEth !== bEth) return aEth ? -1 : 1;
  return a.name.localeCompare(b.name);
}

const ENV_DEFAULT_CHAIN_ID = Number(
  (env.VITE_DEFAULT_CHAIN_ID as string | undefined) ?? SEPOLIA.chainId,
);

/**
 * Read-only fallback chain — used when no wallet is connected, or the wallet
 * is on an unsupported chain. Resolves to the env-chosen chainId if that chain
 * has a Diamond, else falls back to Sepolia (the only always-live Phase-1
 * testnet today). Type is narrowed: `diamondAddress` is guaranteed non-null
 * so call sites that dereference it don't need a null check.
 */
export type DeployedChain = ChainConfig & { diamondAddress: string };

export const DEFAULT_CHAIN: DeployedChain = (() => {
  const envChain = CHAIN_REGISTRY[ENV_DEFAULT_CHAIN_ID];
  if (envChain && envChain.diamondAddress !== null) {
    return envChain as DeployedChain;
  }
  if (SEPOLIA.diamondAddress === null) {
    throw new Error('DEFAULT_CHAIN resolution failed — Sepolia has no diamondAddress');
  }
  return SEPOLIA as DeployedChain;
})();

/**
 * Chain config for the VPFI canonical chain on the current environment
 * (mainnet or testnet). Used by the VPFI panel to show where the canonical
 * adapter lives.
 */
export function getCanonicalVPFIChain(
  preference: 'mainnet' | 'testnet' = DEFAULT_CHAIN.testnet ? 'testnet' : 'mainnet',
): ChainConfig {
  const pool = Object.values(CHAIN_REGISTRY).filter(
    (c) => c.isCanonicalVPFI && c.testnet === (preference === 'testnet'),
  );
  return pool[0] ?? BASE_SEPOLIA;
}

/**
 * Back-compat accessor. Prefer `CHAIN_REGISTRY` + `getChainByChainId`.
 */
export const SUPPORTED_CHAINS = {
  ethereum: ETHEREUM,
  base: BASE,
  polygonZkevm: POLYGON_ZKEVM,
  arbitrum: ARBITRUM,
  optimism: OPTIMISM,
  bnb: BNB,
  sepolia: SEPOLIA,
  baseSepolia: BASE_SEPOLIA,
  polygonZkevmCardona: POLYGON_ZKEVM_CARDONA,
  arbitrumSepolia: ARBITRUM_SEPOLIA,
  optimismSepolia: OPTIMISM_SEPOLIA,
  bnbTestnet: BNB_TESTNET,
} as const;

/** Lookup a chain by its numeric chainId. Returns undefined for chains the
 *  app doesn't recognise at all (e.g. Avalanche, Solana — not in scope for
 *  Phase 1). */
export function getChainByChainId(
  chainId: number | null | undefined,
): ChainConfig | undefined {
  if (chainId == null) return undefined;
  return CHAIN_REGISTRY[chainId];
}

/** True iff a live Phase-1 Diamond exists on this chain. Chains registered
 *  but pending deploy (diamondAddress === null) are NOT supported yet —
 *  protocol calls must be gated on this. */
export function isChainSupported(chainId: number | null | undefined): boolean {
  const c = getChainByChainId(chainId);
  return c !== undefined && c.diamondAddress !== null;
}

/** True iff the chain is known to the app (in the registry) even if the
 *  Diamond isn't deployed there yet. Used to distinguish "unsupported chain"
 *  banners from "pending deploy" messaging. */
export function isChainRegistered(chainId: number | null | undefined): boolean {
  return getChainByChainId(chainId) !== undefined;
}
