#!/usr/bin/env bash
#
# exportLzWatcherVars.sh — emit per-chain wrangler-secret commands
# for the ops/lz-watcher Cloudflare Worker.
#
# The lz-watcher reads ~6 env vars per chain it monitors:
#   RPC_<KEY>                        operator-curated (carries API key)
#   LZ_ENDPOINT_<KEY>                LZ V2 endpoint address
#   ULN302_SEND_LIB_<KEY>            ULN302 send library
#   ULN302_RECV_LIB_<KEY>            ULN302 receive library
#   OAPP_VPFI_OFT_ADAPTER_<KEY>      canonical chain only
#   OAPP_VPFI_MIRROR_<KEY>           mirror chain only
#   OAPP_VPFI_BUY_RECEIVER_<KEY>     canonical chain only
#   OAPP_VPFI_BUY_ADAPTER_<KEY>      mirror chain only
#   OAPP_REWARD_<KEY>                every chain
#   VPFI_TOKEN_<KEY>                 every chain (the local VPFI ERC20)
#
# This script handles ONLY the OAPP_* + VPFI_TOKEN_* family — the ones
# whose values come from `contracts/deployments/<slug>/addresses.json`
# (i.e., things THIS repo deploys). The RPC + LZ_ENDPOINT + ULN302
# bindings are operator-curated and have to come from the operator's
# secret store — see ops/lz-watcher/README.md for those.
#
# Output: a `wrangler secret put` shell snippet on stdout, ready for
# the operator to redirect into a file or `bash`-pipe after eyeball
# review. NEVER pipes itself into wrangler — secrets land via the
# operator's deliberate choice.
#
# The lz-watcher's current shortKey set (per chains.ts) is mainnet-
# only: BASE / ETH / ARB / OP / ZKEVM / BNB. Polygon-PoS isn't there
# yet (per CLAUDE.md "Cross-Chain Security Policy" Polygon PoS is
# Phase 2). Testnet chains are SKIPPED with a friendly note — the
# lz-watcher doesn't gate testnet flows so per-chain LZ-watch on a
# testnet is meaningless.
#
# Usage:
#   bash contracts/script/exportLzWatcherVars.sh                # walk every chain
#   bash contracts/script/exportLzWatcherVars.sh base ethereum  # specific chains
#   bash contracts/script/exportLzWatcherVars.sh > /tmp/lz-vars.sh
#       # then review with `cat /tmp/lz-vars.sh` and run with
#       # `cd ops/lz-watcher && bash /tmp/lz-vars.sh` once happy.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_ROOT="$CONTRACTS_DIR/deployments"

# Map deploy-script chain-slug → lz-watcher's shortKey suffix.
# Keep this map in lockstep with ops/lz-watcher/src/chains.ts:
# adding a new shortKey there means adding it here too.
chain_shortkey() {
  case "$1" in
    base)            echo "BASE" ;;
    ethereum)        echo "ETH" ;;
    arbitrum)        echo "ARB" ;;
    optimism)        echo "OP" ;;
    polygon-zkevm)   echo "ZKEVM" ;;
    bnb)             echo "BNB" ;;
    *)               echo "" ;;
  esac
}

# Pick chains from CLI args, or walk every directory under
# contracts/deployments/ if no args given.
if [ $# -eq 0 ]; then
  CHAINS=()
  if [ -d "$DEPLOY_ROOT" ]; then
    while IFS= read -r d; do
      [ -z "$d" ] && continue
      slug=$(basename "$d")
      CHAINS+=("$slug")
    done < <(find "$DEPLOY_ROOT" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort)
  fi
else
  CHAINS=("$@")
fi

if [ ${#CHAINS[@]} -eq 0 ]; then
  echo "# No chains found — neither passed as args nor under $DEPLOY_ROOT/." >&2
  exit 0
fi

cat <<'BANNER'
#!/usr/bin/env bash
#
# Generated by contracts/script/exportLzWatcherVars.sh.
# Run from inside ops/lz-watcher/ once you've reviewed every value.
# Each `wrangler secret put` is interactive and prompts for the
# secret value; this script automates only the address-bearing
# secrets (which it writes via stdin for non-interactive paste).
#
# RPC + LZ_ENDPOINT + ULN302 secrets are NOT here — those come from
# the operator's curated env (LayerZero docs + paid-tier RPC).

set -euo pipefail
BANNER
echo

SKIPPED_TESTNETS=()
EMITTED=0
for slug in "${CHAINS[@]}"; do
  KEY=$(chain_shortkey "$slug")
  if [ -z "$KEY" ]; then
    SKIPPED_TESTNETS+=("$slug")
    continue
  fi

  ADDR_FILE="$DEPLOY_ROOT/$slug/addresses.json"
  if [ ! -f "$ADDR_FILE" ]; then
    echo "# $slug: no addresses.json at $ADDR_FILE — skipped." >&2
    continue
  fi

  DIAMOND=$(jq -r '.diamond // empty'         "$ADDR_FILE")
  REWARD=$(jq -r  '.vaipakamReward // empty'  "$ADDR_FILE")
  OFT=$(jq -r     '.vpfiOftAdapter // empty'  "$ADDR_FILE")
  MIR=$(jq -r     '.vpfiMirror // empty'      "$ADDR_FILE")
  BREC=$(jq -r    '.vpfiBuyReceiver // empty' "$ADDR_FILE")
  BADP=$(jq -r    '.vpfiBuyAdapter // empty'  "$ADDR_FILE")
  VTOK=$(jq -r    '.vpfiToken // empty'       "$ADDR_FILE")

  echo "# ── $slug ($KEY) ─────────────────────────────────────────────────"

  emit_secret() {
    local var="$1"
    local val="$2"
    [ -z "$val" ] && return 0
    [ "$val" = "null" ] && return 0
    # Heredoc avoids putting the secret on the command line + works
    # even when wrangler runs interactively (it reads stdin if not
    # a TTY).
    printf 'echo -n %q | pnpm exec wrangler secret put %s\n' "$val" "$var"
    EMITTED=$((EMITTED + 1))
  }

  # Reward OApp + VPFI ERC-20 are universal across canonical AND
  # mirror chains — emit unconditionally when present.
  emit_secret "OAPP_REWARD_$KEY" "$REWARD"
  emit_secret "VPFI_TOKEN_$KEY"  "$VTOK"

  # Canonical chain (Base / Base-Sepolia) carries OFT-Adapter +
  # Buy-Receiver. Mirror chains carry the inverse pair. The
  # omit-keys policy in CLAUDE.md means addresses.json only ever
  # has ONE side of each pair populated for any given chain —
  # emit_secret skips empties so this branch is just a clean
  # all-six-attempts loop.
  emit_secret "OAPP_VPFI_OFT_ADAPTER_$KEY"  "$OFT"
  emit_secret "OAPP_VPFI_MIRROR_$KEY"       "$MIR"
  emit_secret "OAPP_VPFI_BUY_RECEIVER_$KEY" "$BREC"
  emit_secret "OAPP_VPFI_BUY_ADAPTER_$KEY"  "$BADP"

  # Diamond isn't in the lz-watcher's read set today, but emit it
  # commented so the operator has the address handy if a future
  # watcher rule keys on Diamond events.
  [ -n "$DIAMOND" ] && [ "$DIAMOND" != "null" ] && \
    echo "# DIAMOND_$KEY = $DIAMOND  (not currently consumed by lz-watcher)"

  echo
done

if [ ${#SKIPPED_TESTNETS[@]} -gt 0 ]; then
  echo "# ── Skipped (lz-watcher has no shortKey for these) ─────────────"
  for slug in "${SKIPPED_TESTNETS[@]}"; do
    echo "#   $slug"
  done
  echo "# Add a shortKey case to ops/lz-watcher/src/chains.ts AND a matching"
  echo "# branch in chain_shortkey() of this script if you want them included."
  echo
fi

echo "# Done. $EMITTED secret(s) staged for $((${#CHAINS[@]} - ${#SKIPPED_TESTNETS[@]})) chain(s)."
