import { getDeployment } from '@vaipakam/contracts/deployments';

/**
 * Typed env bindings for the apps/indexer Worker.
 *
 * Slimmed from the ops/hf-watcher monolith env so this Worker only
 * sees what it actually needs. Stage 3 PR3 of the Worker split
 * (see `docs/DesignsAndPlans/Stage3WorkerSplitPlan.md`) splits the
 * indexer-only bindings out from the keeper / agent surfaces:
 *
 *   - `DB`                            — D1 binding (this Worker
 *                                       writes the offers / loans /
 *                                       activity tables; keeper +
 *                                       agent read them via the
 *                                       same shared database).
 *   - `RPC_*`                         — per-chain RPC URLs for the
 *                                       chain-event scan + the
 *                                       live-ownership multicalls
 *                                       in /loans/by-lender etc.
 *                                       Polygon Amoy is INCLUDED here
 *                                       (loanRoutes consults it for
 *                                       chain-id → RPC mapping); not
 *                                       Polygon mainnet (no Diamond
 *                                       there in Phase 1).
 *   - `CANCELLED_OFFER_RETENTION_DAYS` — int days; the
 *                                       cancelled-offer retention
 *                                       cron drops rows older than
 *                                       this. Default 30 inside the
 *                                       prune helper.
 *
 * What's deliberately NOT here (lives on apps/{keeper,agent}):
 *   - QUOTE_*_RATELIMIT / SCAN_BLOCKAID_RATELIMIT /
 *     DIAG_RECORD_RATELIMIT — agent (HTTP rate-limit buckets)
 *   - DIAG_SAMPLE_RATE / DIAG_RETENTION_DAYS — agent
 *   - TG_BOT_TOKEN / TG_BOT_USERNAME / PUSH_CHANNEL_PK — keeper +
 *     agent (notification dispatch)
 *   - KEEPER_PRIVATE_KEY / KEEPER_ENABLED — keeper
 *   - ZEROEX_API_KEY / ONEINCH_API_KEY — keeper (server-side
 *     liquidation quoting) + agent (public quote proxies)
 *   - FRONTEND_ORIGIN — indexer routes use OPEN CORS (T-041
 *     "public chain-indexer reads"), no per-origin gate
 *
 * Diamond addresses come from `@vaipakam/contracts/deployments` (the
 * consolidated `deployments.json` exported by
 * `contracts/script/exportFrontendDeployments.sh`). Same artifact
 * the frontend + keeper Workers read.
 */
export interface Env {
  DB: D1Database;

  // Per-chain RPC URLs — chain-event scan + live-ownership multicalls.
  // Each missing URL skips that chain this tick.
  RPC_BASE?: string;
  RPC_ETH?: string;
  RPC_ARB?: string;
  RPC_OP?: string;
  RPC_ZKEVM?: string;
  RPC_BNB?: string;
  RPC_SEPOLIA?: string;
  RPC_BASE_SEPOLIA?: string;
  RPC_ARB_SEPOLIA?: string;
  RPC_OP_SEPOLIA?: string;
  RPC_BNB_TESTNET?: string;
  RPC_POLYGON_AMOY?: string;

  // 2026-05-08 — cancelled-offer retention in days. The chainIndexer
  // stamps `cancelled_at` when an OfferCanceled / OfferClosed
  // (reason=2) event lands; the cron-driven prune in
  // cancelledOfferRetention.ts drops rows past this window. Default
  // 30. String → int coerce + clamp at >= 1.
  CANCELLED_OFFER_RETENTION_DAYS?: string;
}

export interface ChainConfig {
  id: number;
  name: string;
  rpc: string;
  diamond: string;
}

/**
 * Resolve chain configs from env + the consolidated deployments
 * JSON imported via `@vaipakam/contracts/deployments`. Chains with
 * no RPC configured OR no Diamond deployment recorded are filtered
 * out — the indexer's chain scan skips them this tick.
 *
 * Adding a chain = one entry here + matching RPC secret +
 * `contracts/deployments/<slug>/addresses.json` regenerated by the
 * post-deploy export script. No JSON schema change.
 *
 * Polygon Amoy is included here (loanRoutes /loans/by-* paths
 * consult the chain-id → RPC mapping for live-ownership reads).
 * Polygon mainnet stays absent — no Diamond there in Phase 1.
 */
export function getChainConfigs(env: Env): ChainConfig[] {
  const meta: { id: number; name: string; rpc: string | undefined }[] = [
    // Mainnets — included once both the deployment artifact and the
    // matching RPC secret land.
    { id: 8453, name: 'Base', rpc: env.RPC_BASE },
    { id: 1, name: 'Ethereum', rpc: env.RPC_ETH },
    { id: 42161, name: 'Arbitrum', rpc: env.RPC_ARB },
    { id: 10, name: 'Optimism', rpc: env.RPC_OP },
    { id: 1101, name: 'Polygon zkEVM', rpc: env.RPC_ZKEVM },
    { id: 56, name: 'BNB Chain', rpc: env.RPC_BNB },
    // Testnets — pre-mainnet phase indexes these too.
    { id: 84532, name: 'Base Sepolia', rpc: env.RPC_BASE_SEPOLIA },
    { id: 11155111, name: 'Sepolia', rpc: env.RPC_SEPOLIA },
    { id: 421614, name: 'Arbitrum Sepolia', rpc: env.RPC_ARB_SEPOLIA },
    { id: 11155420, name: 'Optimism Sepolia', rpc: env.RPC_OP_SEPOLIA },
    { id: 80002, name: 'Polygon Amoy', rpc: env.RPC_POLYGON_AMOY },
    { id: 97, name: 'BNB Testnet', rpc: env.RPC_BNB_TESTNET },
  ];
  const out: ChainConfig[] = [];
  for (const m of meta) {
    if (!m.rpc) continue;
    const dep = getDeployment(m.id);
    if (!dep) continue;
    out.push({
      id: m.id,
      name: m.name,
      rpc: m.rpc,
      diamond: dep.diamond,
    });
  }
  return out;
}
