#!/usr/bin/env node
/**
 * Build-time sitemap.xml + robots.txt generator for
 * alpha02.vaipakam.com (same one-script-both-files pattern as
 * apps/www/scripts/generate-sitemap.mjs — robots.txt names the
 * sitemap URL, so generating both in one pass guarantees they agree).
 *
 * Indexing policy (mirrors SeoMeta.tsx — keep the two in sync):
 *   - PUBLIC_ROUTES below are the generic product surfaces — listed
 *     in the sitemap, no robots restrictions.
 *   - Wallet-gated, per-user surfaces (/positions, /claims, /vault,
 *     /activity, /settings, /faucet) are NOT Disallowed here —
 *     deliberately. A robots.txt Disallow prevents crawling but NOT
 *     indexing of the bare URL if it's linked from elsewhere; the
 *     reliable "never index" signal is the noindex the crawler can
 *     only see by fetching the page (SeoMeta's <meta name="robots">
 *     + the X-Robots-Tag rules in public/_headers).
 *
 * No hreflang alternates yet — alpha02's language is a cookie/device
 * preference, not a URL dimension, and TRANSLATED_LOCALES is
 * English-only. When locale URL routing lands (see I18nPlan.md), lift
 * the per-locale <xhtml:link> block from www's generator.
 *
 * Wired to `prebuild` in package.json; output lands in `public/`,
 * which Vite copies verbatim into `dist/`.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const ORIGIN = (
  process.env.VITE_ALPHA02_PUBLIC_ORIGIN ?? 'https://alpha02.vaipakam.com'
).replace(/\/+$/, '');

/** Indexable routes — mirrors the `index: true` rows in
 *  src/components/SeoMeta.tsx. Order: likely-importance for a
 *  crawler's first-pass scan. */
const PUBLIC_ROUTES = [
  '/',
  '/borrow',
  '/lend',
  '/rent',
  '/offers',
  '/desk',
  '/vpfi',
  '/nft',
  '/help',
];

function buildSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ];
  for (const route of PUBLIC_ROUTES) {
    lines.push('  <url>');
    lines.push(`    <loc>${ORIGIN}${route === '/' ? '/' : route}</loc>`);
    lines.push(`    <lastmod>${today}</lastmod>`);
    lines.push(`    <priority>${route === '/' ? '1.0' : '0.7'}</priority>`);
    lines.push('  </url>');
  }
  lines.push('</urlset>');
  return lines.join('\n') + '\n';
}

function buildRobots() {
  return [
    '# Vaipakam connected app (alpha02) — public crawl policy.',
    '# Generated by apps/alpha02/scripts/generate-seo.mjs',
    `# at ${new Date().toISOString()}`,
    '#',
    '# Per-user surfaces are excluded from the index via noindex',
    '# (meta tag + X-Robots-Tag in _headers), NOT via Disallow —',
    '# see the generator header for why.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n');
}

const publicDir = resolve(__dirname, '..', 'public');
mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'sitemap.xml'), buildSitemap());
writeFileSync(resolve(publicDir, 'robots.txt'), buildRobots());
console.log(
  `[seo] wrote sitemap.xml (${PUBLIC_ROUTES.length} URLs) + robots.txt → ${publicDir}`,
);
