/**
 * T-042 Phase 4 — Safe governance handoff composer.
 *
 * For every "Propose change" button on the admin dashboard, we
 * compose the calldata for the target setter and hand the operator
 * off to Safe (https://app.safe.global). The dashboard NEVER signs
 * the proposal — Safe owns the multisig signing flow.
 *
 * Safe's current web app does NOT honour a `?txs=` query on
 * `/transactions/queue` (that URL only lists already-proposed txs).
 * The supported path is:
 *
 *   1. Open Transaction Builder inside Safe (`/apps/open?appUrl=…`).
 *   2. Import a Transaction Builder JSON batch (the format tx-builder
 *      exports/downloads).
 *
 * `buildSafeHandoff` returns both the builder URL and an importable
 * batch file; `openSafeGovernanceHandoff` downloads the JSON and
 * opens Safe in a new tab.
 *
 * Phase 4 explicitly does NOT wrap the call inside a TimelockController
 * `schedule` — the protocol's governance topology already routes
 * Safe → TimelockController via the Safe's transaction-execution
 * delegate, and the timelock proposal queue (T-042 reads it
 * separately for the "pending change" indicator) reflects the
 * post-Safe-approval state.
 */

import { encodeFunctionData, type Abi } from 'viem';
import type { KnobMeta } from './protocolConsoleKnobs';

/** Hosted Transaction Builder Safe App (see safe-wallet-monorepo
 *  `useTxBuilderApp.ts`). */
const TX_BUILDER_APP_URL = 'https://apps-portal.safe.global/tx-builder';

/** Per-network Safe app EIP-3770 prefix. */
const EIP3770_PREFIX_BY_CHAIN_ID: Record<number, string> = {
  1: 'eth',
  10: 'oeth',
  56: 'bnb',
  137: 'matic',
  8453: 'base',
  42161: 'arb1',
  11155111: 'sep',
  84532: 'basesep',
  421614: 'arb-sep',
  11155420: 'op-sep',
  97: 'bnbtest',
  80002: 'pol-amoy',
};

export interface SafeDeepLinkParams {
  /** Connected Safe address (the multisig that will sign). */
  safe: string;
  /** Target chain id. */
  chainId: number;
  /** The diamond address (or other target contract) for the call. */
  to: string;
  /** Encoded calldata for the setter. */
  data: string;
  /** Native value to send. Always 0 for governance writes. */
  value?: string;
}

/** Transaction Builder batch file (custom-hex-data row shape). */
export interface SafeTxBatchFile {
  version: '1.0';
  chainId: string;
  createdAt: number;
  meta: {
    name: string;
    description: string;
    createdFromSafeAddress: string;
    createdFromOwnerAddress: string;
  };
  transactions: Array<{
    to: string;
    value: string;
    data: string;
  }>;
}

export interface SafeHandoff {
  /** Opens Safe with Transaction Builder loaded for this Safe. */
  txBuilderUrl: string;
  /** Import this file in Transaction Builder → upload JSON batch. */
  batchFile: SafeTxBatchFile;
  batchFileName: string;
  /** Copy-paste fallback if import is skipped. */
  transaction: {
    to: string;
    value: string;
    data: string;
  };
}

export interface SafeHandoffMeta {
  batchName?: string;
  description?: string;
}

/**
 * Build a Safe governance handoff package. Returns `null` when the
 * chain isn't Safe-supported (e.g. anvil-localhost).
 */
export function buildSafeHandoff(
  p: SafeDeepLinkParams,
  meta?: SafeHandoffMeta,
): SafeHandoff | null {
  const prefix = EIP3770_PREFIX_BY_CHAIN_ID[p.chainId];
  if (!prefix) return null;

  const safeIdentifier = `${prefix}:${p.safe}`;
  const txBuilderUrl =
    `https://app.safe.global/apps/open?` +
    `safe=${encodeURIComponent(safeIdentifier)}` +
    `&appUrl=${encodeURIComponent(TX_BUILDER_APP_URL)}`;

  const transaction = {
    to: p.to,
    value: p.value ?? '0',
    data: p.data,
  };

  const batchName = meta?.batchName ?? 'Vaipakam governance proposal';
  const batchFile: SafeTxBatchFile = {
    version: '1.0',
    chainId: String(p.chainId),
    createdAt: Date.now(),
    meta: {
      name: batchName,
      description:
        meta?.description ?? 'Generated by Vaipakam protocol console',
      createdFromSafeAddress: p.safe,
      createdFromOwnerAddress: '',
    },
    transactions: [transaction],
  };

  const slug =
    batchName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 48) || 'vaipakam-proposal';

  return {
    txBuilderUrl,
    batchFile,
    batchFileName: `${slug}.json`,
    transaction,
  };
}

/** Trigger a browser download of the Transaction Builder batch JSON. */
export function downloadSafeTxBatch(handoff: SafeHandoff): void {
  const blob = new Blob([JSON.stringify(handoff.batchFile, null, 2)], {
    type: 'application/json',
  });
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = objectUrl;
  anchor.download = handoff.batchFileName;
  anchor.click();
  URL.revokeObjectURL(objectUrl);
}

/** Download the batch file and open Safe Transaction Builder. */
export function openSafeGovernanceHandoff(handoff: SafeHandoff): void {
  downloadSafeTxBatch(handoff);
  window.open(handoff.txBuilderUrl, '_blank', 'noopener,noreferrer');
}

/**
 * @deprecated Use `buildSafeHandoff` — returns only the Transaction
 * Builder URL (the old `?txs=` queue deep-link is not supported by
 * Safe's current web app).
 */
export function buildSafeDeepLink(p: SafeDeepLinkParams): string | null {
  return buildSafeHandoff(p)?.txBuilderUrl ?? null;
}

/**
 * Encode the calldata for a knob's setter given a single new value.
 */
export function encodeKnobSetCall(
  knob: KnobMeta,
  diamondAbi: Abi,
  args: ReadonlyArray<string | number | bigint | boolean>,
): `0x${string}` {
  if (args.length !== knob.setter.args.length) {
    throw new Error(
      `encodeKnobSetCall: expected ${knob.setter.args.length} args for ${knob.setter.fn}, got ${args.length}`,
    );
  }
  const coerced = args.map((raw, i) => coerceArg(raw, knob.setter.args[i].type));
  return encodeFunctionData({
    abi: diamondAbi,
    functionName: knob.setter.fn,
    args: coerced,
  });
}

function coerceArg(raw: string | number | bigint | boolean, solType: string): unknown {
  if (typeof raw === 'boolean') return raw;
  if (typeof raw === 'bigint') return raw;
  if (solType === 'bool') {
    if (typeof raw === 'string') return raw === 'true' || raw === '1';
    return Boolean(raw);
  }
  if (solType === 'address') return raw as string;
  if (solType === 'bytes32') return raw as string;
  if (solType === 'string') return raw as string;
  if (typeof raw === 'number') return BigInt(raw);
  if (typeof raw === 'string') return BigInt(raw);
  return raw;
}