/**
 * wagmi v2 configuration — single source of truth for the chain + connector
 * set the UI talks to. Consumers wire this into the provider stack in
 * `main.tsx` via `<WagmiProvider config={wagmiConfig}>`.
 *
 * Design rules:
 *   - The chain list is mirrored from `contracts/config.ts` so wagmi,
 *     ConnectKit, and our existing screens agree on "supported chains"
 *     without two sources of truth drifting.
 *   - RPC transports route through the same env-configurable URLs we use
 *     for read-only calls, so wagmi-driven writes and our viem-based
 *     reads observe the same node (avoids the "wallet sees one state,
 *     UI sees another" class of bug).
 *   - Connectors are provided via ConnectKit's `getDefaultConfig` helper —
 *     it wires the injected + WalletConnect + Coinbase Wallet paths with
 *     ConnectKit's branded metadata so the picker shows wallet icons and
 *     names, and (on mobile) the curated deep-link list.
 *
 * Connector set: ConnectKit's stock connectors — `injected({ target:
 * 'metaMask' })`, `coinbaseWallet()`, `walletConnect({ showQrModal:
 * false })`, plus the `safe()` App connector. The list is hand-rolled
 * (rather than taken from `getDefaultConfig`'s `.connectors`) for ONE
 * reason: to set `metadata.redirect: { universal: <origin> }` on the
 * WalletConnect connector — WC-v2 wallets honour it and navigate back
 * to the dApp after the user approves, so the wallet app returns the
 * user to the browser instead of leaving them to app-switch back.
 *
 * History note (May 2026), so the next person doesn't re-tread it:
 *   - We briefly swapped MetaMask's injected connector for wagmi's
 *     `metaMask()` (`@metamask/sdk` wrapper) to deep-link the featured
 *     tile on a mobile browser. It regressed desktop — the bundled
 *     `@metamask/sdk` failed to detect the installed extension and
 *     showed its own QR. Reverted. Known limitation that brings back:
 *     on a mobile browser the featured "MetaMask" tile shows
 *     ConnectKit's QR-scan screen rather than deep-linking; the
 *     "All Wallets" → MetaMask entry (no dedicated connector → falls
 *     through to WalletConnect + `metamask://wc?uri=…`) does open the
 *     app. Don't re-add `metaMask()` until its extension detection is
 *     reliable.
 *   - The WalletConnect `metadata.redirect` had `native: ""` — an
 *     empty `native` makes WC v2's `EthereumProvider` fail to produce a
 *     pairing URI, so the QR screen / "All Wallets" list hung
 *     "loading". Fixed by passing ONLY `universal` (below). Don't add a
 *     `native` value unless the web app actually registers a custom URL
 *     scheme.
 */
import { createConfig, fallback, http, webSocket } from "wagmi";
import type { Transport } from "viem";
import { coinbaseWallet, injected, safe, walletConnect } from "wagmi/connectors";
import {
  mainnet,
  base,
  baseSepolia,
  polygonZkEvm,
  polygonZkEvmCardona,
  bsc,
  bscTestnet,
  arbitrum,
  arbitrumSepolia,
  optimism,
  optimismSepolia,
  sepolia,
  foundry,
  type Chain,
} from "wagmi/chains";
import { getDefaultConfig } from "connectkit";
import { CHAIN_REGISTRY } from "../contracts/config";

const WC_PROJECT_ID =
  (
    import.meta.env.VITE_WALLETCONNECT_PROJECT_ID as string | undefined
  )?.trim() || "";

// NOTE: an earlier change disabled WalletConnect on desktop (only
// passed the project id through on mobile) to suppress Chrome's
// "Allow this site to access other apps and services on this device?"
// popup that fires when a desktop user clicks a mobile-wallet
// deep-link entry in the modal. That change was reverted because it
// also killed the desktop QR-code flow — the QR code is generated by
// the WalletConnect connector itself, so without it the modal hangs
// at "loading" and a desktop user with no extension can't pair their
// mobile wallet at all. The popup is annoying but only fires on the
// explicit mobile-wallet click path; the QR-scan flow doesn't trigger
// it. Treat the popup as expected user-initiated behaviour rather
// than disable a load-bearing connector.

const APP_NAME = "Vaipakam";
const APP_DESCRIPTION =
  "Vault-to-Vault lending fully on-chain. Lend and borrow tokens, rent NFTs, " +
  "set your own terms — every position tracked by a unique NFT.";
const APP_URL =
  typeof window !== "undefined"
    ? window.location.origin
    : "https://vaipakam.com";
const APP_ICON = `${APP_URL}/logo-light.png`;

/**
 * Chain-object table keyed by chainId. Maps the viem-provided chain objects
 * to the ones our UI already supports. Any chainId in CHAIN_REGISTRY that
 * isn't in this table would be skipped by the connector — keep in sync
 * when a new chain is added to contracts/config.ts.
 */
const CHAIN_BY_ID: Record<number, Chain> = {
  [mainnet.id]: mainnet,
  [base.id]: base,
  [baseSepolia.id]: baseSepolia,
  [polygonZkEvm.id]: polygonZkEvm,
  [polygonZkEvmCardona.id]: polygonZkEvmCardona,
  [bsc.id]: bsc,
  [bscTestnet.id]: bscTestnet,
  [arbitrum.id]: arbitrum,
  [arbitrumSepolia.id]: arbitrumSepolia,
  [optimism.id]: optimism,
  [optimismSepolia.id]: optimismSepolia,
  [sepolia.id]: sepolia,
  // Anvil — viem's prebuilt chain id 31337. Surfaced so wagmi /
  // ConnectKit can switch the wallet to a local foundry node for
  // Range Orders Phase 1 smoke tests against
  // `contracts/script/anvil-bootstrap.sh`. Only paired with
  // CHAIN_REGISTRY's ANVIL entry on dev — production-built bundles
  // include it but no production user will ever see Anvil offered
  // unless they're already on chain 31337 in their wallet.
  [foundry.id]: foundry,
};

/** Build the ordered chain list from the registry. Preserves the canonical
 *  display order (compareChainsForDisplay) so the wallet-picker presents
 *  chains in the same order as the rest of the UI. */
const supportedChains = Object.values(CHAIN_REGISTRY)
  .map((c) => CHAIN_BY_ID[c.chainId])
  .filter((c): c is Chain => Boolean(c));

if (supportedChains.length === 0) {
  throw new Error(
    "wagmi config: CHAIN_REGISTRY resolved to zero viem-known chains — " +
      "extend CHAIN_BY_ID in this file when adding a new supported chain.",
  );
}

/** Transports override the viem default (public RPC) with the RPC URL we
 *  ship in CHAIN_REGISTRY (env-configurable). This keeps the wallet session
 *  and our dashboard's read layer pinned to the same upstream.
 *
 *  #1031 (reverse-ported from alpha02's chain/wagmi.ts):
 *  - `batch: true` folds same-tick eth_calls into one JSON-RPC batch —
 *    per-row token reads on list pages go from hundreds of HTTP
 *    requests to a handful, with zero call-site changes.
 *  - When a chain has a WebSocket RPC configured (`_WSS_URL` env var,
 *    opt-in per deploy), it is wrapped in a `fallback` AHEAD of HTTP:
 *    viem's block watcher then rides `eth_subscribe` (newHeads) and
 *    any WS hiccup transparently drops to the HTTP transport. No WS
 *    URL ⇒ plain HTTP, identical to before. */
const transports: Record<number, Transport> = {};
for (const c of Object.values(CHAIN_REGISTRY)) {
  if (CHAIN_BY_ID[c.chainId]) {
    const httpTransport = http(c.rpcUrl, { batch: true });
    transports[c.chainId] = c.wsUrl
      ? fallback([webSocket(c.wsUrl), httpTransport])
      : httpTransport;
  }
}

// Type assertion: `getDefaultConfig` expects `[Chain, ...Chain[]]`. We've
// guarded above that the array has at least one element.
type NonEmptyChains = readonly [Chain, ...Chain[]];

// ConnectKit wires the usual browser-extension + WalletConnect + Coinbase
// Wallet connectors via `getDefaultConfig`. Merge in wagmi's Safe-App
// connector so when Vaipakam is embedded in a Safe multisig UI as a
// Safe App, the iframe handshake auto-completes and the connected Safe
// becomes the signer. The Safe connector is a no-op outside a Safe
// iframe context (the iframe postMessage handshake never completes,
// the connector stays dormant), so adding it never affects the normal
// browser flow.
const defaultConnectKitConfig = getDefaultConfig({
  chains: supportedChains as unknown as NonEmptyChains,
  transports,
  walletConnectProjectId: WC_PROJECT_ID,
  appName: APP_NAME,
  appDescription: APP_DESCRIPTION,
  appUrl: APP_URL,
  appIcon: APP_ICON,
  // ConnectKit v1.9+ ships an opt-in third-party account integration as default —
  // adding the @aave/account smart-wallet connector and rendering a
  // the third-party CTA at the top of the picker. We do NOT want a
  // competing-protocol-branded button at the top of Vaipakam's connect
  // modal; opt out explicitly. Removes the connector AND the CTA.
  enableAaveAccount: false,
  // Keep wagmi's auto-reconnect on page reload (default true) so a user
  // who just refreshed doesn't have to re-pair their wallet every time.
  ssr: false,
});

export const wagmiConfig = createConfig({
  ...defaultConnectKitConfig,
  // Hand-rolled connector list = ConnectKit's stock set, but with
  // `metadata.redirect: { universal }` on the WalletConnect connector
  // (see the file header). Chains / transports / app metadata still
  // come from `getDefaultConfig` above; only `connectors` is ours.
  connectors: [
    // MetaMask — injected-target connector (ConnectKit's default).
    // Direct extension connect on desktop; QR-scan screen on a mobile
    // browser (the deep-link path on mobile is the "All Wallets" →
    // MetaMask entry, which uses the WalletConnect connector below).
    injected({ target: "metaMask" }),
    // Coinbase Wallet — stock SDK connector.
    coinbaseWallet({ appName: APP_NAME, appLogoUrl: APP_ICON }),
    // WalletConnect — only wired when a project id is configured.
    // `showQrModal: false` keeps ConnectKit rendering its own QR /
    // redirect UI. `metadata.redirect` carries ONLY `universal` (a web
    // dApp has no native URL scheme; an empty `native` breaks pairing-
    // URI generation, see header) so WC-v2 wallets bring the user back
    // to the dApp after they approve.
    ...(WC_PROJECT_ID
      ? [
          walletConnect({
            projectId: WC_PROJECT_ID,
            showQrModal: false,
            metadata: {
              name: APP_NAME,
              description: APP_DESCRIPTION,
              url: APP_URL,
              icons: [APP_ICON],
              redirect: { universal: APP_URL },
            },
          }),
        ]
      : []),
    // Safe-App connector — no-op outside a Safe iframe. Trust only
    // Safe's first-party domains for the handshake; wider matches would
    // let arbitrary sites impersonate a Safe context.
    safe({
      allowedDomains: [/app\.safe\.global$/, /safe\.global$/],
      debug: false,
    }),
  ],
});

/** Whether WalletConnect is available in this build. Mirrors the flag
 *  callers used to read from `isWalletConnectConfigured()`. */
export const walletConnectAvailable = WC_PROJECT_ID.length > 0;

/** Alias retained so the misconfiguration warning in `main.tsx` keeps
 *  compiling. After the desktop-revert there's no longer a separate
 *  "configured but suppressed this session" state — both flags collapse
 *  to whether the env var is set. */
export const walletConnectConfigured = walletConnectAvailable;
